// Fetch only the 12 segmented PLY files (about 2 MB) from the 3.9 GB OpenEar ZIP.
// curl is used because the public Zenodo endpoint rejects Node fetch in this environment.
// Usage: node fetch-openear.mjs <output-directory>. Requires curl and Node with zlib.crc32.
import fs from 'node:fs';import path from 'node:path';import {execFileSync}from 'node:child_process';import {inflateRawSync,crc32}from 'node:zlib';import crypto from 'node:crypto';
const url='https://zenodo.org/records/1473724/files/ZETA.zip?download=1';const dir=path.resolve(process.argv[2]||'../../tmp/atlas-qa/source-openear');fs.mkdirSync(dir,{recursive:true});
function range(start,end){return execFileSync('curl.exe',['-sS','--fail','--range',end===undefined?String(start):`${start}-${end}`,'--max-time','60',url],{encoding:null,maxBuffer:8*1024*1024,windowsHide:true})}
const tail=range('-65536'),e=tail.lastIndexOf(Buffer.from([0x50,0x4b,5,6]));if(e<0)throw Error('ZIP directory not found');const size=tail.readUInt32LE(e+12),offset=tail.readUInt32LE(e+16);if(size>2*1024*1024)throw Error('Unexpected ZIP directory size');const central=range(offset,offset+size-1),entries=[];
for(let i=0;i<central.length;){if(central.readUInt32LE(i)!==0x02014b50)throw Error('Bad central header');const n=central.readUInt16LE(i+28),extra=central.readUInt16LE(i+30),comment=central.readUInt16LE(i+32),name=central.toString('utf8',i+46,i+46+n);if(/^07_3D_Models\/\d\d_[A-Za-z ]+\.ply$/.test(name))entries.push({name,crc:central.readUInt32LE(i+16),compressed:central.readUInt32LE(i+20),bytes:central.readUInt32LE(i+24),offset:central.readUInt32LE(i+42)});i+=46+n+extra+comment}
if(entries.length!==12)throw Error('Source file set changed');const start=Math.min(...entries.map(e=>e.offset)),end=Math.max(...entries.map(e=>e.offset+e.compressed+2048));if(end-start>4*1024*1024)throw Error('Unexpected source range');const bytes=range(start,end),audit=[];
for(const f of entries){const o=f.offset-start;if(bytes.readUInt32LE(o)!==0x04034b50||bytes.readUInt16LE(o+8)!==8)throw Error('Bad local header');const n=bytes.readUInt16LE(o+26),extra=bytes.readUInt16LE(o+28);if(bytes.toString('utf8',o+30,o+30+n)!==f.name)throw Error('Filename mismatch');const data=inflateRawSync(bytes.subarray(o+30+n+extra,o+30+n+extra+f.compressed));if(data.length!==f.bytes||crc32(data)!==f.crc)throw Error('CRC mismatch');const name=path.basename(f.name);fs.writeFileSync(path.join(dir,name),data);audit.push({file:name,sha256:crypto.createHash('sha256').update(data).digest('hex'),zipCrcVerified:true})}
fs.writeFileSync(path.join(dir,'download-audit.json'),JSON.stringify({source:url,license:'CC-BY-4.0',files:audit},null,2));console.log('Verified',audit.length,'OpenEar PLY files');
