export const additions = [
 {id:'kidneys',name:'신장',english:'Kidneys',system:'비뇨기계',color:'#b68b89',position:'배 · 후복막',description:'혈액을 여과하고 수분과 전해질 균형을 조절하는 한 쌍의 장기.',files:['VH_M_Kidney_L.glb','VH_M_Kidney_R.glb'],landmarks:['양쪽 신장과 신장문을 원본 좌표로 함께 표시합니다.','겉질·속질 등 원본에 포함된 내부 구획도 보존합니다.'],links:[['질환','만성콩팥병','chronic-kidney-disease'],['검사','신기능 검사','renal-function'],['개념','네프론','nephron']]},
 {id:'pancreas',name:'췌장',english:'Pancreas',system:'소화기계',color:'#c8ad7d',position:'배 · 위 뒤쪽',description:'소화 효소와 혈당 조절 호르몬을 분비하는 장기.',files:['VH_M_Pancreas.glb'],landmarks:['머리·몸통·꼬리의 연속적인 형상을 유지합니다.','단독 모델의 화면 크기는 실제 장기 크기 비교용이 아닙니다.'],links:[['질환','췌장염','pancreatitis'],['검사','복부 CT','abdominal-ct'],['개념','인슐린','insulin']]},
 {id:'spleen',name:'비장',english:'Spleen',system:'림프·면역계',color:'#ae869f',position:'배 · 좌상복부',description:'혈액을 걸러내고 면역 반응에 관여하는 림프 기관.',files:['VH_M_Spleen.glb'],landmarks:['왼쪽 상복부의 원본 위치 관계를 유지합니다.','회전하여 볼록한 면과 안쪽의 비장문을 살펴보세요.'],links:[['질환','비장비대','splenomegaly'],['검사','복부 초음파','abdominal-ultrasound'],['개념','림프계','lymphatic-system']]},
 {id:'small-intestine',name:'소장',english:'Small intestine',system:'소화기계',color:'#c99782',position:'배 · 복강',description:'음식물을 소화하고 대부분의 영양소를 흡수하는 소화관.',files:['VH_M_Small_Intestine.glb'],landmarks:['장관의 굽이와 연결을 임의로 다시 배치하지 않습니다.','전체 보기에서 다른 복부 장기에 가려질 수 있습니다.'],links:[['질환','크론병','crohn-disease'],['검사','소장 검사','small-bowel-examination'],['개념','영양소 흡수','nutrient-absorption']]},
 {id:'colon',name:'대장',english:'Large intestine',system:'소화기계',color:'#b99378',position:'배 · 복강에서 골반',description:'수분을 흡수하고 대변을 형성·이동시키는 소화관.',files:['SBU_M_Intestine_Large.glb'],landmarks:['큰창자의 구획과 굽이를 원본 형상으로 표시합니다.','다른 자료의 모델이므로 전신 좌표 정합을 별도로 확인합니다.'],links:[['질환','대장암','colorectal-cancer'],['검사','대장내시경','colonoscopy'],['개념','대장 운동','colonic-motility']]},
 {id:'bladder',name:'방광',english:'Urinary bladder',system:'비뇨기계',color:'#c69696',position:'골반 · 치골 뒤',description:'신장에서 만들어진 소변을 일시적으로 저장하는 장기.',files:['VH_M_Urinary_Bladder.glb'],landmarks:['골반 내 원본 위치를 유지합니다.','표시된 크기와 형상은 방광 충만도에 따른 모든 변이를 대표하지 않습니다.'],links:[['질환','방광염','cystitis'],['검사','요검사','urinalysis'],['개념','배뇨','micturition']]},
 {id:'ureters',name:'요관',english:'Ureters',system:'비뇨기계',color:'#c9ad87',position:'배에서 골반 · 후복막',description:'양쪽 신장에서 방광으로 소변을 운반하는 관.',files:['VH_M_Ureter_L.glb','VH_M_Ureter_R.glb'],landmarks:['왼쪽과 오른쪽 요관을 함께 표시합니다.','가느다란 구조여서 확대하면 관의 경로를 보기 쉽습니다.'],links:[['질환','요관결석','ureteric-stone'],['검사','요로 CT','urinary-tract-ct'],['개념','요 흐름','urine-flow']]},
 {id:'prostate',name:'전립선',english:'Prostate',system:'생식기계',color:'#b799a7',position:'남성 골반 · 방광 아래',description:'정액의 일부를 구성하는 분비물을 만드는 남성 생식샘.',files:['VH_M_Prostate.glb'],landmarks:['남성 기준 모델입니다.','방광 아래의 전립선 위치를 원본 좌표로 유지합니다.'],links:[['질환','전립선비대증','bph'],['검사','PSA 검사','psa'],['개념','남성 생식계','male-reproductive-system']]},
 {id:'spinal-cord',name:'척수',english:'Spinal cord',system:'신경계',color:'#b6a5c6',position:'척추관',description:'뇌와 몸 사이의 신호 전달 및 반사에 관여하는 중추신경계 구조.',files:['VH_M_Spinal_Cord.glb'],landmarks:['길이와 굵기 변화를 원본 그대로 유지합니다.','척수와 척추뼈는 서로 다른 구조입니다. 이 항목은 척수입니다.'],links:[['질환','척수손상','spinal-cord-injury'],['검사','척수 MRI','spinal-mri'],['개념','척수 반사','spinal-reflex']]},
 {id:'eyes',name:'눈',english:'Eyes',system:'감각계',color:'#a2b5b6',position:'머리 · 안와',description:'빛을 받아 시각 정보를 만드는 한 쌍의 감각 기관.',files:['VH_M_Eye_L.glb','VH_M_Eye_R.glb'],landmarks:['양쪽 안구를 원본 위치 관계로 함께 표시합니다.','외부에서 가려지는 내부 구성요소는 메시로 보존하되 임의로 노출하지 않습니다.'],links:[['질환','녹내장','glaucoma'],['검사','안저 검사','fundoscopy'],['개념','시각 경로','visual-pathway']]},
 {id:'thymus',name:'흉선',english:'Thymus',system:'림프·면역계',color:'#c8a9a3',position:'가슴 · 앞위 종격동',description:'T 림프구의 성숙에 관여하는 면역 기관.',files:['VH_M_Thymus.glb'],landmarks:['앞쪽 종격동의 원본 위치를 유지합니다.','흉선은 연령에 따른 형태 차이가 큰 기관입니다.'],links:[['질환','흉선종','thymoma'],['검사','흉부 CT','chest-ct'],['개념','T 림프구','t-lymphocyte']]},
 {id:'skin',name:'피부',english:'Skin',system:'피부계',color:'#d0b6a0',position:'몸의 표면',description:'몸을 덮어 보호하고 감각과 체온 조절에 관여하는 기관.',files:['VH_M_Skin.glb'],landmarks:['전신 외표면을 하나의 탐색 대상으로 표시합니다.','피부의 미세한 조직 층을 재현하는 모델은 아닙니다.'],links:[['질환','피부염','dermatitis'],['검사','피부 검사','skin-examination'],['개념','피부 장벽','skin-barrier']]}
];
const reproductive = [
 {id:'uterus',name:'자궁',english:'Uterus',system:'생식기계',color:'#c695a2',position:'여성 골반',description:'임신 시 배아와 태아가 발달하는 근육성 기관.',files:['VH_F_Uterus.glb'],overview:false,landmarks:['여성 기준 원본 해부 모델입니다.','남성 기준 전신 지도에는 합성하지 않고 단독으로 탐색합니다.'],links:[['질환','자궁근종','uterine-fibroid'],['검사','골반 초음파','pelvic-ultrasound'],['개념','자궁내막','endometrium']]},
 {id:'ovaries',name:'난소',english:'Ovaries',system:'생식기계',color:'#c3a6bd',position:'여성 골반 · 자궁 양쪽',description:'난자를 성숙시키고 생식 호르몬을 분비하는 한 쌍의 기관.',files:['VH_F_Ovary_L.glb','VH_F_Ovary_R.glb'],overview:false,landmarks:['양쪽 난소의 원본 위치 관계를 유지합니다.','생리주기·연령에 따른 모든 형태 변이를 대표하지 않습니다.'],links:[['질환','난소낭종','ovarian-cyst'],['검사','골반 초음파','pelvic-ultrasound'],['개념','배란','ovulation']]},
 {id:'fallopian-tubes',name:'난관',english:'Uterine tubes',system:'생식기계',color:'#d0a99f',position:'여성 골반 · 자궁 위가쪽',description:'난소 근처에서 자궁으로 이어지는 한 쌍의 관.',files:['VH_F_Fallopian_Tube_L.glb','VH_F_Fallopian_Tube_R.glb'],overview:false,landmarks:['양쪽 난관의 경로와 말단 형상을 유지합니다.','남성 기준 전신 지도에는 표시하지 않습니다.'],links:[['질환','난관 임신','tubal-pregnancy'],['검사','자궁난관조영술','hsg'],['개념','수정','fertilization']]},
 {id:'placenta',name:'태반',english:'Placenta',system:'생식기계',color:'#bc888c',position:'임신 · 자궁 내',description:'임신 중 모체와 태아 사이의 물질 교환에 관여하는 기관.',files:['VH_F_Placenta.glb'],overview:false,landmarks:['태반 단독 자료이며 비임신 전신 모델에 배치하지 않습니다.','원본에서 확인되는 표면과 연결부만 표시합니다.'],links:[['질환','전치태반','placenta-previa'],['검사','산과 초음파','obstetric-ultrasound'],['개념','태반 순환','placental-circulation']]}
];
additions.push(...reproductive);

import {extended} from './extended.js';additions.push(...extended);
