import {getDiseaseCatalog} from './data-provider.js';
import {diseaseMappings} from './disease-mappings.js';
export function mountDiseaseBrowser({onScenario,onNavigate}){
 const trigger=document.createElement('button');trigger.className='body-button';trigger.textContent='질병 목록·분류';trigger.id='disease-browser-open';document.querySelector('.intro').append(trigger);
 const dialog=document.createElement('dialog');dialog.id='disease-browser';dialog.innerHTML='<div class="catalog-heading"><h2>기존 웹앱 질병 목록</h2><button aria-label="질병 목록 닫기" id="disease-browser-close">×</button></div><p id="catalog-status">목록을 준비합니다.</p><div class="disease-filters"><input id="disease-query" type="search" placeholder="질병·별칭 검색" aria-label="질병 검색"><select id="disease-specialty" aria-label="질병 분과"><option value="">전체 분과</option></select><select id="disease-class" aria-label="질병 분류"><option value="">전체 분류</option></select></div><p class="slice-note">원본의 분과·분류·상위 질환 체계를 유지합니다. 질병 문서가 있다는 것과 3D 병태 모델이 구현되었다는 것은 다릅니다.</p><div id="disease-results"></div>';document.body.append(dialog);dialog.querySelector('#disease-browser-close').onclick=()=>dialog.close();let catalog;
 async function load(){try{catalog=await getDiseaseCatalog();const select=dialog.querySelector('#disease-specialty');select.replaceChildren(new Option('전체 분과',''));[...new Set(catalog.diseases.map(d=>d.specialty))].sort().forEach(s=>select.add(new Option(s,s)));classes();render();}catch{dialog.querySelector('#catalog-status').textContent='목록을 불러오지 못했습니다. 닫았다가 다시 열어 재시도하세요.';}}
 function classes(){const specialty=dialog.querySelector('#disease-specialty').value,select=dialog.querySelector('#disease-class');select.replaceChildren(new Option('전체 분류',''));[...new Set(catalog.diseases.filter(d=>!specialty||d.specialty===specialty).flatMap(d=>d.classification))].sort().forEach(c=>select.add(new Option(c,c)));}
 function render(){const text=dialog.querySelector('#disease-query').value.toLowerCase(),specialty=dialog.querySelector('#disease-specialty').value,classification=dialog.querySelector('#disease-class').value;const all=catalog.diseases.filter(d=>(!specialty||d.specialty===specialty)&&(!classification||d.classification.includes(classification))&&(!text||(d.title+' '+(d.aliases||[]).join(' ')).toLowerCase().includes(text)));dialog.querySelector('#catalog-status').textContent=catalog.diseases.length+'개 문서 · '+new Set(catalog.diseases.map(d=>d.specialty)).size+'개 분과 · 검색 '+all.length+'개'+(all.length>80?' (앞 80개 표시 · 검색으로 좁혀보세요)':'');const host=dialog.querySelector('#disease-results');host.replaceChildren();for(const d of all.slice(0,80)){const article=document.createElement('article'),h=document.createElement('h3'),meta=document.createElement('p');h.textContent=d.title;meta.textContent=[d.specialty,d.category,...d.classification].join(' › ');article.append(h,meta);if(d.familyMeta?.parentDisease){const parent=document.createElement('p');parent.textContent='상위 질환: '+d.familyMeta.parentDisease+' · '+(d.familyMeta.population||'');article.append(parent);}const link=diseaseMappings.find(m=>m.diseaseId===d.id);const state=document.createElement('small');state.textContent=link?'교육용 3D 시나리오 연결됨':'3D 병태 시나리오 미연결';article.append(state);if(link){const scope=document.createElement('p');scope.className='slice-note';scope.textContent=link.scopeNote;article.append(scope);const apply=document.createElement('button');apply.textContent='3D 예시 보기';apply.onclick=()=>{dialog.close();onScenario(link)};article.append(apply);}const open=document.createElement('button');open.textContent='문서 연결 정보';open.onclick=()=>onNavigate(d);article.append(open);host.append(article);}}
 trigger.onclick=()=>{dialog.showModal();load()};dialog.querySelector('#disease-specialty').onchange=()=>{classes();render()};dialog.querySelector('#disease-class').onchange=render;dialog.querySelector('#disease-query').oninput=()=>{if(catalog)render()};
}
