import './host-integration.css';
import {explosionAssembly} from './explosion-assemblies.js';
import {selectionEnglishName} from './selection-labels.js';
import {lightModels} from './light-model-manifest.js';
import {detailOptions,buildDetailModel} from './anatomical-details.js';
import {indexStructure,matchesStructure} from './structure-search.js';
import {contextGroupFor} from './context-groups.js';
import {compilePathologyStates,resolvePathologyTarget} from './pathology-targets.js';
import {sourceLaterality} from './laterality.js';
import {getStructureIdentity,findStructureIdentities} from './structure-identifiers.js';
import {mountDiseaseBrowser} from './disease-browser.js';
import {configureDataProvider,saveAtlasView} from './data-provider.js';
import {modelSources} from './model-sources.js';
import {pathology,physiologicalMotion} from './pathology.js';
import {coverage,availableRoutes} from './inspection-data.js';
import './style.css';
import {organs,stateDefinitions,createOrganState,validateState} from './data.js';
import {anatomy} from './anatomy.js';
import {ModelRepository} from './reference-models.js';
import {AtlasScene} from './scene.js';
let detailMode='';const $=s=>document.querySelector(s);let selected=organs.some(o=>o.id===new URLSearchParams(location.search).get('organ'))?new URLSearchParams(location.search).get('organ'):'heart',view=selected,panelOpen=true,panelTab='structure';const states=createOrganState();
import {organIcons as icons} from './organ-icons.js';
const icon=id=>`<svg viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[id]||'M14 3C5 3 3 10 5 17C7 25 21 25 23 17C25 10 23 3 14 3ZM8 14H20M14 8V20'}"/></svg>`;
$('#app').innerHTML=`<header><a class="brand" href="#"><span class="brandmark">m<span>·</span></span><span>the medicine<span class="brand-sub">INTERACTIVE COLLECTION</span></span></a><span class="prototype"><i></i> 독립 프로토타입 <span> / 01</span></span></header>
<main><section class="intro"><div><span class="eyebrow">A SMALL WORLD WITHIN</span><h1>작은 인체도감<span>.</span></h1><p>하나의 장기에서, 연결된 지식으로.</p></div><button id="body" class="body-button">◎ <span>전체 인체 보기</span> ↗</button></section>
<div class="workspace"><nav class="organ-nav" aria-label="장기 선택"><div class="nav-label">COLLECTION <span>${organs.length}</span></div><div class="catalog-controls"><input id="organ-search" type="search" placeholder="장기 찾기" aria-label="장기 이름 검색"><select id="system-filter" aria-label="시스템 필터"><option value="">전체 시스템</option>${[...new Set(organs.map(o=>o.system))].map(s=>`<option value="${s}">${s}</option>`).join('')}</select></div><div id="organ-list">${organs.map((o,i)=>`<button class="organ-button" data-organ="${o.id}" aria-pressed="${o.id===selected}" style="--organ:${o.color}"><span class="organ-icon">${icon(o.id)}</span><span class="organ-text"><b>${o.name}</b><small>${o.english}</small></span><span class="organ-index">${String(i+1).padStart(2,'0')}</span></button>`).join('')}</div><p id="no-results" hidden>검색 결과가 없어요.</p><div class="nav-foot">${organs.length}개의 장기와 구조.<br>하나씩, 더 깊이 살펴보세요.</div></nav>
<section class="exhibit" aria-label="3D 장기 탐색"><div class="scene-head"><span id="scene-system">심혈관계</span><span>3D EXPLORER</span></div><div id="viewport"><span id="hover-label" hidden></span><div id="fallback" hidden>3D 화면을 사용할 수 없습니다. 장기 메뉴로 정보를 탐색할 수 있어요.</div></div><div class="specimen"><span id="specimen-number">SPECIMEN 03 / 04</span><h2 id="specimen-name">Heart</h2><span id="view-tag">심장 · 단독 보기</span></div><div class="angle-controls" aria-label="해부 시점"><button data-angle="front">앞</button><button data-angle="side">옆</button><button data-angle="back">뒤</button><button data-angle="bottom">아래</button></div><div class="view-controls"><button id="zoom-out" aria-label="축소">−</button><button id="reset" aria-label="시점 초기화">↺</button><button id="zoom-in" aria-label="확대">＋</button><button id="info" aria-label="정보 카드 열기" hidden>정보</button></div><p class="gesture">드래그로 회전 <span>·</span> 휠 / 두 손가락으로 확대 <span>·</span> 우클릭 드래그로 이동</p></section>
<aside id="panel" aria-label="장기 정보"><div class="card-top"><span class="eyebrow">ORGAN NOTES</span><button id="close" aria-label="정보 카드 닫기">×</button></div><div class="panel-tabs" role="tablist" aria-label="장기 탐색 탭"><button data-panel-tab="info" role="tab">정보</button><button data-panel-tab="structure" role="tab">구조</button><button data-panel-tab="pathology" role="tab">병태</button></div><div id="card-content" aria-live="polite"></div><section id="pathology-tools" hidden></section><section id="structure-tools" hidden></section><section class="state-section"><div class="state-heading"><b>상태 레이어</b><span>효과 미리보기</span></div><div class="states" role="group" aria-label="시각 상태">${Object.entries(stateDefinitions).map(([id,s])=>`<button data-state="${id}" aria-pressed="${id==='normal'}">${s.label}</button>`).join('')}</div><label class="intensity" for="intensity">효과 강도 <input id="intensity" type="range" min="0" max="100" value="65"><output id="intensity-value">65%</output></label><p class="state-note">색과 크기 변화는 시각 효과 예시입니다.<br>실제 병변의 형태·정도를 재현하지 않습니다.</p></section></aside>
<svg id="connector" aria-hidden="true"><path/><circle r="4"/></svg></div>
<footer><span><i></i> 형태를 탐색하고, 지식을 연결하세요.</span><span><a href="./CREDITS.html" target="_blank" rel="noopener noreferrer">3D · HuBMAP HRA · CC BY 4.0 ↗</a><b>VOL. 01</b></span></footer></main>
<dialog id="link-dialog"><button id="dialog-close" aria-label="닫기">×</button><span class="eyebrow">RELATED KNOWLEDGE</span><h2 id="link-title"></h2><p id="link-detail"></p><p class="dialog-note">현재는 독립 프로토타입입니다. 앱 통합 시 이 항목을 기존 지식 문서로 연결합니다.</p><button id="dialog-ok">도감으로 돌아가기</button></dialog>`;
let scene;const repository=new ModelRepository();let requestId=0;let contextEnabled=false;const hasAnatomicalContext=id=>contextEnabled&&!!contextGroupFor(id);
function render(){applyPanelTab();if($('#structure-tools'))$('#structure-tools').hidden=true;const o=organs.find(o=>o.id===selected);document.documentElement.style.setProperty('--selected',o.color);document.querySelectorAll('[data-organ]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.organ===selected&&view!=='body'));$('#card-content').innerHTML=`<span class="card-system">${o.system}</span><h2>${o.name}<span>${o.english}</span></h2><p class="description">${o.description}</p><div class="location"><span>위치</span>${o.position}</div><div class="related-heading">연결된 지식 <span>${String(o.links.length).padStart(2,'0')}</span></div><div class="related">${o.links.map(([type,label,key])=>`<button data-link="${key}"><small>${type}</small><span>${label}</span><span>↗</span></button>`).join('')}</div><details class="anatomy-notes"><summary>해부 구조 살펴보기</summary><ul>${anatomy[o.id].landmarks.map(l=>`<li>${l}</li>`).join('')}</ul><a href="${anatomy[o.id].reference}" target="_blank" rel="noopener noreferrer">${anatomy[o.id].source} ↗</a><p>좌우는 인체 기준입니다. 아래 세부 구조 도구에서 내부를 살펴볼 수 있습니다.</p></details>`;
 $('#scene-system').textContent=view==='body'?'BODY OVERVIEW':o.system;$('#specimen-number').textContent=view==='body'?'MALE REFERENCE BODY':`SPECIMEN ${String(organs.indexOf(o)+1).padStart(2,'0')} / ${organs.length}`;$('#specimen-name').textContent=view==='body'?'Together':o.english;$('#view-tag').textContent=view==='body'?'남성 기준 · 시스템 필터로 내부를 살펴보세요':`${o.name} · ${['uterus','ovaries','fallopian-tubes','placenta'].includes(o.id)?'여성 자료 · ':''}단독 보기`;$('#body span').textContent=view==='body'?'장기 단독 보기':'전체 인체 보기';$('#card-content').hidden=view==='body';$('.state-section').hidden=view==='body';syncState();$('#panel').classList.toggle('closed',!panelOpen);$('#info').hidden=panelOpen;$('#connector').classList.toggle('hidden',!panelOpen||view==='body');$('#panel').classList.remove('enter');void $('#panel').offsetWidth;$('#panel').classList.add('enter');$('#connector').classList.remove('draw');void $('#connector').getBoundingClientRect();$('#connector').classList.add('draw');renderInspection();renderPathology();
}
function syncState(){document.querySelectorAll('[data-state]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.state===states[selected].effect));$('#intensity').value=states[selected].intensity*100;$('#intensity').disabled=states[selected].effect==='normal';$('#intensity-value').textContent=Math.round(states[selected].intensity*100)+'%';scene?.setState(states[selected])}
function select(id){detailMode='';window.dispatchEvent(new CustomEvent('atlas:select',{detail:{organId:id}}));selected=id;view=id;panelOpen=true;render();showView(id)}
async function initialize(){try{$('#fallback').hidden=false;$('#fallback').textContent='해부 모델을 준비하고 있어요…';const initial=await repository.get(selected);const models={[selected]:initial};$('#fallback').hidden=true;scene=new AtlasScene($('#viewport'),{models,onSelect:(id,partId)=>{if(view==='body'||!partId){select(id);return;}panelOpen=true;panelTab='structure';render();scene.inspect({part:partId,organ:'',route:'',side:'',mode:'isolate',slice:false});scene.focusPart();renderInspection();syncPresentationControls();window.dispatchEvent(new CustomEvent('atlas:structure-select',{detail:{organId:id,partId}}));},onHover:(id,label)=>{$('#hover-label').hidden=!id;$('#hover-label').textContent=label||organs.find(o=>o.id===id)?.name||''},onProject:p=>{const base=$('.workspace').getBoundingClientRect(),v=$('#viewport').getBoundingClientRect(),card=$('#panel').getBoundingClientRect();const x=p.x+v.left-base.left,y=p.y+v.top-base.top;const mobile=innerWidth<=800;const endX=mobile?card.left-base.left+card.width*.5:card.left-base.left,endY=mobile?card.top-base.top:card.top-base.top+112;$('#connector').setAttribute('viewBox',`0 0 ${base.width} ${base.height}`);$('#connector path').setAttribute('d',mobile?`M${x},${y} C${x},${y+45} ${endX},${endY-35} ${endX},${endY}`:`M${x},${y} C${x+70},${y} ${endX-60},${endY} ${endX},${endY}`);$('#connector circle').setAttribute('cx',x);$('#connector circle').setAttribute('cy',y);$('#connector').style.visibility=p.visible?'visible':'hidden'}})}catch(e){$('#fallback').hidden=false;$('#fallback').textContent='해부 모델을 불러오지 못했습니다. 새로고침해 주세요. 장기 정보는 아래 메뉴로 볼 수 있어요.';console.error(e);document.querySelectorAll('.view-controls button:not(#info)').forEach(b=>b.disabled=true)}
await showView(view);syncState();const initialScenario=new URLSearchParams(location.search).get('scenario');if(scene&&pathology[view]?.some(p=>p.id===initialScenario)){scene.setPathology({id:initialScenario,intensity:.65});panelTab='pathology';applyPanelTab();renderPathology();}window.parent.postMessage({type:'atlas:ready'},location.origin);}
initialize();
$('.organ-nav').addEventListener('click',e=>{const b=e.target.closest('[data-organ]');if(b)select(b.dataset.organ)});$('#body').onclick=()=>{detailMode='';view=view==='body'?selected:'body';panelOpen=view!=='body';render();showView(view)};$('#close').onclick=()=>{panelOpen=false;render();$('#info').focus()};$('#info').onclick=()=>{panelOpen=true;render();$('#close').focus()};$('#reset').onclick=()=>scene?.reset();$('#zoom-in').onclick=()=>scene?.zoom(.85);$('#zoom-out').onclick=()=>scene?.zoom(1.15);
$('.states').onclick=e=>{const b=e.target.closest('[data-state]');if(b&&validateState(selected,b.dataset.state)){states[selected].effect=b.dataset.state;syncState()}};$('#intensity').oninput=e=>{states[selected].intensity=Number(e.target.value)/100;syncState()};$('#card-content').onclick=e=>{const b=e.target.closest('[data-link]');if(!b)return;const o=organs.find(o=>o.id===selected),link=o.links.find(l=>l[2]===b.dataset.link);const proceed=window.dispatchEvent(new CustomEvent('atlas:navigate',{cancelable:true,detail:{organId:selected,kind:link[0],label:link[1],contentKey:link[2]}}));if(!proceed)return;$('#link-title').textContent=link[1];$('#link-detail').textContent=`${o.name} → ${link[0]} → ${link[1]}`;$('#link-dialog').showModal()};$('#dialog-close').onclick=$('#dialog-ok').onclick=()=>$('#link-dialog').close();render();
document.querySelectorAll('[data-angle]').forEach(b=>b.onclick=()=>scene?.setAngle(b.dataset.angle));
window.addEventListener('pagehide',()=>scene?.dispose());

window.addEventListener('atlas:set-state',e=>{const {organId,effect,intensity=.65}=e.detail||{};if(!validateState(organId,effect)||!Number.isFinite(intensity))return;states[organId]={effect,intensity:Math.min(1,Math.max(0,intensity))};if(selected===organId)syncState()});

async function showView(id){
 if(!scene)return;const token=++requestId;const host=$('#viewport'),canvas=host.querySelector('canvas');delete host.dataset.model;canvas.hidden=true;$('#fallback').hidden=false;$('#fallback').textContent=id==='body'?'전신의 장기를 준비하고 있어요…':'선택한 해부 모델을 불러오고 있어요…';$('#connector').classList.add('loading');
 try{const model=detailMode?buildDetailModel(id,detailMode):hasAnatomicalContext(id)?await repository.getAnatomicalContext(id):await repository.get(id,(n,total)=>{if(token===requestId)$('#fallback').textContent='전신 모델 준비 · '+n+' / '+total});if(token!==requestId)return;scene.replaceModel(id,model);scene.setView(id);for(const [key,old]of Object.entries(scene.models))if(key!==id){scene.scene.remove(old);delete scene.models[key]}repository.releaseInactive(id,model);if(hasAnatomicalContext(id)||detailMode)scene.baseSide="";scene.setOverviewFilter($('#system-filter').value);syncState();canvas.hidden=false;$('#fallback').hidden=true;$('#connector').classList.remove('loading');host.dataset.model=id;host.dataset.context=hasAnatomicalContext(id)?contextGroupFor(id).id:"single";if(hasAnatomicalContext(id))$("#view-tag").textContent=contextGroupFor(id).label;scene.inspect({});if(scene.baseSide)scene.setSide(scene.baseSide);syncPresentationControls();renderInspection();renderPathology();}
 catch(error){if(token!==requestId)return;$('#fallback').textContent='모델을 불러오지 못했어요. 다른 장기를 선택하거나 다시 시도하세요.';const retry=document.createElement('button');retry.textContent='다시 시도';retry.onclick=()=>showView(id);$('#fallback').append(retry);}
}
function filterCatalog(){const text=$('#organ-search').value.trim().toLowerCase(),system=$('#system-filter').value;let count=0;document.querySelectorAll('[data-organ]').forEach(b=>{const o=organs.find(o=>o.id===b.dataset.organ);const visible=(!system||o.system===system)&&(o.name+' '+o.english).toLowerCase().includes(text);b.hidden=!visible;if(visible)count++});$('#no-results').hidden=count>0;scene?.setOverviewFilter(system);}
$('#organ-search').addEventListener('input',filterCatalog);$('#system-filter').addEventListener('change',filterCatalog);

function renderInspection(){const host=$('#structure-tools');if(!scene||$('#viewport').dataset.model!==view)return;host.hidden=false;const parts=scene.getParts().filter(p=>!scene.baseSide||sourceLaterality(p.id)===scene.baseSide).map(indexStructure);host.innerHTML='<details open class="structure-details"><summary>세부 구조 · '+parts.length+'개</summary><p class="coverage-note"></p><input id="part-search" type="search" placeholder="구조 이름·용어 ID 검색" aria-label="세부 구조 검색"><select id="part-picker" aria-label="세부 구조 선택"><option value="">전체 구조</option></select><p id="structure-identity" class="slice-note"></p><div class="inspection-row"><select id="part-mode" aria-label="구조 표시 방식"><option value="all">전체 보기</option><option value="context">주변 투명</option><option value="isolate">선택만 보기</option></select><select id="part-side" aria-label="좌우 구조"><option value="">양쪽</option><option value="L">좌측 표기</option><option value="R">우측 표기</option></select></div><select id="vessel-route" aria-label="구조 경로"><option value="">모든 경로</option></select><label class="slice-toggle"><input type="checkbox" id="slice-toggle"> 앞쪽을 열어 내부 보기</label><input id="slice-position" type="range" min="0" max="100" value="50" aria-label="절개 위치"><p class="slice-note">절개는 표면을 잘라 내부를 드러냅니다. 절단면 조직을 새로 생성하지 않습니다.</p><button id="focus-structure">선택 구조 확대</button><button id="restore-structures">구조 표시 초기화</button><a href="./ANATOMY_AUDIT.html" target="_blank" rel="noopener">전체 검수표 · 포함/누락 구조 ↗</a></details>';
 host.querySelector('.coverage-note').textContent=detailMode?scene.models[scene.active].userData.detail.notice:view==='body'?'남성 기준 조합. 혈관을 함께 배치하며 심장 항목과 같은 이름의 혈관은 중복 제거했습니다. 서로 다른 출처의 접합은 검토 중입니다.':coverage[view];
 if(!detailMode&&contextGroupFor(view)){const context=contextGroupFor(view);const label=document.createElement('label');label.className='slice-toggle';const toggle=document.createElement('input');toggle.type='checkbox';toggle.id=context.controlId;toggle.checked=contextEnabled;label.append(toggle,document.createTextNode(context.label));host.querySelector('.coverage-note').before(label);toggle.onchange=()=>{contextEnabled=toggle.checked;render();showView(view)};if(contextEnabled)host.querySelector('.coverage-note').textContent=context.description;}
 const organPicker=document.createElement('select');organPicker.id='inspection-organ';organPicker.setAttribute('aria-label','조합 내 장기 강조');organPicker.add(new Option('모든 장기',''));const members=hasAnatomicalContext(view)?contextGroupFor(view).members:view==='body'?[...new Set(parts.map(p=>p.organId))]:[];members.forEach(id=>organPicker.add(new Option(organs.find(o=>o.id===id).name,id)));organPicker.hidden=!members.length;host.querySelector('.coverage-note').after(organPicker);
 if(detailMode){for(const ref of scene.models[scene.active].userData.detail.references){const a=document.createElement('a');a.href=ref;a.target='_blank';a.rel='noopener noreferrer';a.textContent='상세 구조 근거 · '+new URL(ref).hostname+' ↗';host.querySelector('.coverage-note').after(a);}}const picker=$('#part-picker');const fill=()=>{const previous=picker.value;picker.replaceChildren(new Option('전체 구조',''));const text=$('#part-search').value.toLowerCase();parts.filter(p=>matchesStructure(p,text)).forEach(p=>picker.add(new Option(p.label,p.id)));if([...picker.options].some(o=>o.value===previous))picker.value=previous;};fill();
 if(['vasculature','heart','body'].includes(view)){const legend=document.createElement('p');legend.className='slice-note';legend.textContent='혈관 색: 동맥은 산호색, 정맥은 청록색. 산소포화도를 표시하는 색이 아닙니다.';host.querySelector('.coverage-note').after(legend);}
 const route=$('#vessel-route');const groups=availableRoutes(parts);route.hidden=!groups.length;groups.forEach(({label,pattern,count})=>route.add(new Option(label+' · '+count+'개',pattern)));
 $('#focus-structure').onclick=()=>scene.focusPart();
 const identity=()=>{const record=(view==='body'||hasAnatomicalContext(view))?findStructureIdentities(picker.value)[0]:getStructureIdentity(view,picker.value);$('#structure-identity').textContent=!picker.value?'':record?.review?.status==='needs-review'?'구조 검토 중 · '+record.review.issues.map(i=>i.message).join(' ')+(record.ontologyId?' (원본 ID: '+record.ontologyId+')':''):record?.ontologyId?record.ontologyLabel+' · '+record.ontologyId:'공식 용어 ID 미연결';};const apply=()=>{scene.inspect({organ:organPicker.value,part:picker.value,mode:$('#part-mode').value,side:$('#part-side').value,route:route.value,slice:$('#slice-toggle').checked,cut:Number($('#slice-position').value)});identity();syncPresentationControls();};
 organPicker.onchange=()=>{picker.value='';route.value='';$('#part-side').value='';$('#part-mode').value=organPicker.value?'context':'all';apply();if(organPicker.value)scene.focusPart();else scene.reset();};picker.onchange=()=>{organPicker.value='';route.value='';$('#part-side').value='';$('#part-mode').value=picker.value?'isolate':'all';apply();if(picker.value)scene.focusPart();else scene.reset()};$('#part-search').oninput=()=>{fill();apply()};for(const id of ['part-mode','part-side','slice-toggle','slice-position'])$('#'+id).oninput=apply;route.onchange=()=>{picker.value='';organPicker.value='';$('#part-side').value='';$('#part-mode').value=route.value?'isolate':'all';apply();if(route.value)scene.focusPart();else scene.reset()};$('#restore-structures').onclick=()=>{scene.inspect({part:'',organ:'',mode:'all',route:'',slice:false,cut:50,side:''});scene.reset();renderInspection();syncPresentationControls()};
 const q=scene.inspection;organPicker.value=q.organ||'';picker.value=q.part;$('#part-mode').value=q.mode;$('#part-side').value=q.side;route.value=q.route;$('#slice-toggle').checked=q.slice;$('#slice-position').value=q.cut;identity();
}

function renderPathology(){const host=$('#pathology-tools');if(detailMode){host.hidden=false;host.textContent='확대 구조 모형에서는 병태 변형을 적용하지 않습니다. 기본 장기 보기에서 국소 부위를 선택하세요.';return;}if(!scene||$('#viewport').dataset.model!==view){host.hidden=true;return;}const previousOrgan=host.querySelector('#scenario-organ')?.value;host.hidden=false;host.replaceChildren();const heading=document.createElement('h3');heading.textContent='정상과 병태생리';host.append(heading);const organSelect=document.createElement('select');organSelect.id='scenario-organ';organSelect.setAttribute('aria-label','시나리오 장기');const context=hasAnatomicalContext(view)?contextGroupFor(view):null;organs.filter(o=>context?context.members.includes(o.id):view!=='body'||o.overview!==false).forEach(o=>organSelect.add(new Option(o.name,o.id)));organSelect.value=(context?.members.includes(previousOrgan)||view==='body'&&previousOrgan)?previousOrgan:view==='body'?selected:view;if(!organSelect.value)organSelect.value='heart';organSelect.hidden=view!=='body'&&!context;host.append(organSelect);
const picker=document.createElement('select');picker.id='pathology-picker';picker.setAttribute('aria-label','병태생리 시나리오');const description=document.createElement('p');description.className='scenario-description';const intensity=document.createElement('input');intensity.type='range';intensity.min=0;intensity.max=100;intensity.id='pathology-intensity';intensity.setAttribute('aria-label','병태생리 표현 강도');const label=document.createElement('label');label.textContent='표현 강도 · 임상 중증도와 무관';label.append(intensity);host.append(picker,description,label);const references=document.createElement('p');references.id='scenario-references';references.className='slice-note';description.after(references);const showDescription=()=>{const scenario=pathology[organSelect.value].find(p=>p.id===picker.value);description.textContent=scenario?.change||'기준 해부 구조를 표시합니다.';references.replaceChildren();for(const ref of scenario?.references||[]){let url;try{url=new URL(ref)}catch{continue}if(url.protocol!=='https:')continue;const link=document.createElement('a');link.href=url.href;link.target='_blank';link.rel='noopener noreferrer';link.textContent='병태 표현 근거 · '+url.hostname+' ↗';references.append(link,document.createElement('br'));}references.hidden=!references.childElementCount;};
const side=document.createElement('select');side.id='pathology-side';side.setAttribute('aria-label','병태 적용 측');const sideLabel=document.createElement('label');sideLabel.textContent='적용 측 · 인체 기준';sideLabel.append(side);host.append(sideLabel);const updateSides=()=>{const previous=side.value;const scenario=pathology[organSelect.value].find(p=>p.id===picker.value);const parts=scene.getParts().filter(p=>getStructureIdentity(organSelect.value,p.id)&&scenario&&new RegExp(scenario.target).test(p.id));const sides=new Set(parts.map(p=>sourceLaterality(p.id)).filter(Boolean));side.replaceChildren(new Option('전체 대상',''));for(const [value,label] of [['L','좌측'],['R','우측']])if(sides.has(value))side.add(new Option(label,value));side.value=sides.has(previous)?previous:'';sideLabel.hidden=sides.size===0;side.disabled=sides.size===0;};
const local=document.createElement('select');local.id='pathology-local';local.setAttribute('aria-label','국소 병태 적용 부위');const localLabel=document.createElement('label');localLabel.textContent='국소 표시 · 해당 구조 안으로 범위 제한';localLabel.append(local);host.append(localLabel);const fillLocal=()=>{const previous=local.value,scenario=pathology[organSelect.value].find(p=>p.id===picker.value);local.replaceChildren(new Option('전체 대상 구조',''));scene.getParts().filter(p=>getStructureIdentity(organSelect.value,p.id)&&scenario&&new RegExp(scenario.target).test(p.id)&&(!side.value||sourceLaterality(p.id)===side.value)).forEach(p=>local.add(new Option(p.label,p.id)));local.value=[...local.options].some(o=>o.value===previous)?previous:'';local.disabled=!scenario;};
 const compare=document.createElement('button');compare.id='compare-normal';compare.textContent=scene.normalComparison?'병태 상태로 돌아가기':'정상과 비교';compare.setAttribute('aria-pressed',String(scene.normalComparison));compare.onclick=()=>{scene.normalComparison=!scene.normalComparison;scene.dirty=true;scene.transitionUntil=performance.now()+500;renderPathology()};const motion=document.createElement('button');motion.id='motion-toggle';motion.textContent=scene.motionPlaying?'모션 일시정지':'모션 재생';motion.setAttribute('aria-pressed',String(scene.motionPlaying));motion.onclick=()=>{scene.setMotion(!scene.motionPlaying);renderPathology()};const speed=document.createElement('input');speed.type='range';speed.min=.25;speed.max=2;speed.step=.25;speed.value=scene.motionSpeed;speed.setAttribute('aria-label','모션 속도');speed.oninput=()=>scene.setMotion(scene.motionPlaying,Number(speed.value));host.append(compare,motion,speed);const note=document.createElement('p');note.className='slice-note';note.textContent='심장·폐는 수축/호흡 개념 모션, 나머지는 병변 강조 모션입니다. 실제 혈류·조직 역학을 계산하는 시뮬레이션은 아닙니다.';host.append(note);
const targetBox=document.createElement('details');targetBox.id='pathology-targets';const targetSummary=document.createElement('summary'),targetPicker=document.createElement('select'),targetFocus=document.createElement('button');targetPicker.id='pathology-target-picker';targetPicker.setAttribute('aria-label','병태 적용 구조');targetFocus.id='pathology-target-focus';targetFocus.textContent='이 구조 확대';targetBox.append(targetSummary,targetPicker,targetFocus);host.append(targetBox);const refreshTargets=()=>{const previous=targetPicker.value;const candidates=compilePathologyStates(scene.pathologyStates,scene.normalComparison);const parts=scene.getParts().filter(p=>resolvePathologyTarget(p.id,candidates)?.organId===organSelect.value);targetSummary.textContent='현재 적용 구조 · '+parts.length+'개';targetPicker.replaceChildren();parts.forEach(p=>targetPicker.add(new Option(p.label,p.id)));if(parts.some(p=>p.id===previous))targetPicker.value=previous;targetPicker.disabled=!parts.length;targetFocus.disabled=!parts.length;};targetFocus.onclick=()=>{if(!targetPicker.value)return;const targetSide=sourceLaterality(targetPicker.value);if(scene.baseSide&&targetSide)scene.baseSide=targetSide;scene.inspect({organ:'',part:targetPicker.value,mode:'context',side:'',route:'',slice:false});scene.focusPart();renderInspection();};
 const fill=()=>{const id=organSelect.value;const available=pathology[id].length>0;picker.disabled=!available;intensity.disabled=!available;compare.disabled=!available;motion.disabled=!available;if(!available)note.textContent='이 장기의 병태·모션 시나리오는 아직 구현하지 않았습니다.';picker.replaceChildren(new Option('정상',''));pathology[id].forEach(p=>picker.add(new Option(p.label,p.id)));const state=scene.pathologyStates[id]||{id:'',intensity:.65};picker.value=state.id||'';intensity.value=state.intensity*100;updateSides();side.value=[...side.options].some(o=>o.value===state.side)?state.side:'';fillLocal();local.value=[...local.options].some(o=>o.value===state.partId)?state.partId:'';showDescription();refreshTargets();};const apply=()=>{scene.setPathology({organId:organSelect.value,id:picker.value,side:side.value,partId:local.value,intensity:Number(intensity.value)/100});showDescription();refreshTargets();};organSelect.onchange=fill;picker.onchange=()=>{updateSides();fillLocal();apply();};side.onchange=()=>{fillLocal();apply()};local.onchange=()=>{apply();if(local.value){const selectedSide=sourceLaterality(local.value);if(scene.baseSide&&selectedSide)scene.baseSide=selectedSide;scene.inspect({organ:'',part:local.value,mode:'context',side:'',route:'',slice:false});scene.focusPart();renderInspection();syncPresentationControls();}};intensity.oninput=apply;fill();
}

mountDiseaseBrowser({onScenario:async mapping=>{detailMode='';selected=mapping.organId;view=selected;panelOpen=true;render();await showView(view);if(scene.active!==mapping.organId)return;scene.setPathology({id:mapping.scenarioId,intensity:.65});panelTab='pathology';applyPanelTab();renderPathology();},onNavigate:d=>{const proceed=window.dispatchEvent(new CustomEvent('atlas:navigate',{cancelable:true,detail:{organId:selected,kind:'질환',contentKey:d.id,diseaseId:d.id,diseaseSlug:d.slug,href:'/disease/'+d.slug,label:d.title}}));if(proceed){$('#link-title').textContent=d.title;$('#link-detail').textContent=d.specialty+' › '+d.classification.join(' › ')+' · 웹앱 연결 경로: /disease/'+d.slug;$('#link-dialog').showModal();}}});
function exportView(){if(!scene||$("#viewport").dataset.model!==view)return null;const parts=scene.getParts(),selectedPart=parts.find(p=>p.id===scene.inspection.part);const memberIds=hasAnatomicalContext(view)?contextGroupFor(view).members:[...new Set(parts.map(p=>p.organId))];return {modelReferences:detailMode?[]:memberIds.map(organId=>({organId,...structuredClone(modelSources[organId]),renderingAsset:repository.quality==='light'&&lightModels[organId]?lightModels[organId].url:modelSources[organId].url})),selectedDetailStructure:selectedPart?.detail||null,selectedStructure:selectedPart?structuredClone(getStructureIdentity(selectedPart.organId,selectedPart.id)):null,detailModel:scene.models[scene.active]?.userData.detail||null,schemaVersion:1,organId:view,context:hasAnatomicalContext(view)?contextGroupFor(view).id:null,modelRevision:detailMode?'schematic-'+detailMode+'-v1':view==='body'?'hra-united-male-v1.10':modelSources[view].sources[0].url,selectedPartId:scene.inspection.part||null,scenarioStates:structuredClone(scene.pathologyStates),presentation:{explodeLayout:'anatomical-assemblies-v1',quality:repository.quality,side:scene.baseSide||null,explode:scene.explodeTarget||0},inspection:{...scene.inspection},camera:{position:scene.camera.position.toArray(),target:scene.controls.target.toArray()},motion:{playing:scene.motionPlaying,speed:scene.motionSpeed,timeSeconds:scene.motionTime}};}
window.organAtlas={configureDataProvider,getStructureIdentity,findStructureIdentities,exportView,saveView:()=>saveAtlasView(exportView())};

function applyPanelTab(){const tab=view==='body'&&panelTab==='info'?'structure':panelTab;$('#panel').dataset.tab=tab;document.querySelectorAll('[data-panel-tab]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.panelTab===tab)));}
document.querySelector('.panel-tabs').onclick=e=>{const b=e.target.closest('[data-panel-tab]');if(b){panelTab=b.dataset.panelTab;applyPanelTab();}};


const presentation=document.createElement('div');presentation.className='presentation-controls';presentation.innerHTML='<label id="detail-model-label">상세 <select id="detail-model" aria-label="해부학 확대 상세 보기"><option value="">기본 장기</option></select></label><label>모델 <select id="model-quality" aria-label="모델 품질"><option value="light">가볍게</option><option value="original">정밀 원본</option></select></label><label id="single-side-label">표시 <select id="single-side" aria-label="장기 한쪽 보기"><option value="L">왼쪽 하나</option><option value="R">오른쪽 하나</option><option value="">양쪽</option></select></label><label>묶음 분해 <input id="explode-view" aria-label="해부 구조 묶음 분해 정도" type="range" min="0" max="100" value="0"><small id="explode-count"></small></label><output id="picked-structure" aria-live="polite"><strong id="selected-english">Select an anatomical structure</strong><small id="selected-korean">모델을 눌러 구조를 선택하세요</small></output><div id="selection-actions" hidden><button id="selection-only" aria-pressed="true">선택한 구조만</button><button id="selection-context" aria-pressed="false">주변 흐리게</button><button id="selection-clear">전체 복원</button></div>';
$('.exhibit').append(presentation);
function syncPresentationControls(){if(!scene)return;const detail=$('#detail-model');detail.replaceChildren(new Option('기본 장기',''));(detailOptions[view]||[]).forEach(([id,label])=>detail.add(new Option(label+' · 확대 모형',id)));detail.value=detailMode;$('#detail-model-label').hidden=!detailOptions[view]||view==='body';$('#single-side-label').hidden=!['eyes','kidneys','ovaries','knees','tonsils'].includes(view)||hasAnatomicalContext(view)||!!detailMode;$('#single-side').value=scene.baseSide||'';const assemblyCount=new Set(scene.getParts().filter(p=>!scene.baseSide||sourceLaterality(p.id)===scene.baseSide).map(p=>explosionAssembly(p.organId,p.id))).size;$('#explode-view').disabled=view==='body'||assemblyCount<2;$('#explode-count').textContent=view==='body'?'':assemblyCount+'묶음';$('#explode-view').title=assemblyCount<2?'이 모델은 하나의 묶음으로 유지합니다':'묶음 내부는 유지하고 묶음 사이만 벌립니다';$('#explode-view').value=(scene.explodeTarget||0)*100;const part=scene.getParts().find(p=>p.id===scene.inspection?.part);$('#selected-english').textContent=part?selectionEnglishName(part):'Select an anatomical structure';$('#selected-korean').textContent=part?.label||'모델을 눌러 구조를 선택하세요';$('#selected-korean').hidden=!!part&&!/[가-힣]/.test(part.label);$('#selection-actions').hidden=!part;$('#selection-only').setAttribute('aria-pressed',String(scene.inspection.mode==='isolate'));$('#selection-context').setAttribute('aria-pressed',String(scene.inspection.mode==='context'));}
$('#single-side').onchange=e=>{scene?.setSide(e.target.value);renderInspection();syncPresentationControls()};
$('#explode-view').oninput=e=>{if(scene&&Number(e.target.value)>0&&(scene.inspection.part||scene.inspection.route||scene.inspection.organ)){scene.inspect({part:'',route:'',organ:'',side:'',mode:'all',slice:false});scene.reset();renderInspection();}scene?.setExplode(Number(e.target.value)/100);syncPresentationControls();if(!scene?.inspection.part)$('#selected-korean').textContent=Number(e.target.value)?'해부학적 묶음 단위로 분리 · 내부 구조의 배치는 유지':'모델을 눌러 구조를 선택하세요'};

$('#model-quality').value=repository.quality;$('#model-quality').onchange=e=>{const url=new URL(location.href);url.searchParams.set('quality',e.target.value);url.searchParams.set('organ',selected);location.assign(url.href)};

$('#detail-model').onchange=e=>{detailMode=e.target.value;contextEnabled=false;showView(view)};

for(const [id,mode]of [['selection-only','isolate'],['selection-context','context']])$('#'+id).onclick=()=>{scene.inspect({mode,slice:false});if(mode==='isolate')scene.focusPart();else if(scene.baseSide){const inspection={...scene.inspection};scene.setSide(scene.baseSide);scene.inspect(inspection);}else scene.reset();renderInspection();syncPresentationControls()};
$('#selection-clear').onclick=()=>{scene.inspect({part:'',organ:'',route:'',side:'',slice:false,mode:'all'});if(scene.baseSide)scene.setSide(scene.baseSide);else scene.reset();renderInspection();syncPresentationControls()};

const selectionLayoutObserver=new ResizeObserver(()=>{const bottom=presentation.offsetTop+presentation.offsetHeight+8;$('.exhibit').style.setProperty('--model-toolbar-bottom',bottom+'px')});selectionLayoutObserver.observe(presentation);window.addEventListener('pagehide',()=>selectionLayoutObserver.disconnect(),{once:true});

// The host owns routes; the isolated viewer owns WebGL and its lifecycle.
window.addEventListener('atlas:navigate',event=>{if(window.parent===window)return;event.preventDefault();window.parent.postMessage({type:'atlas:navigate',detail:event.detail},location.origin)});
window.addEventListener('atlas:select',event=>{if(window.parent!==window)window.parent.postMessage({type:'atlas:select',organId:event.detail.organId},location.origin)});
if(window.parent!==window){document.documentElement.classList.add('hosted-atlas');document.querySelector('.prototype')?.remove();}

window.addEventListener('pagehide',()=>scene?.dispose(),{once:true});
document.addEventListener('visibilitychange',()=>{if(!scene)return;scene.last=performance.now();scene.dirty=true;scene.renderer.setAnimationLoop(document.hidden?null:t=>scene.frame(t));});
