import {disposeDetailModel} from './detail-resources.js';
import {selectionEnglishName} from './selection-labels.js';
import {prepareGroupedExplosion} from './grouped-explosion.js';
import {getStructureIdentity} from './structure-identifiers.js';
import {focusDistance,fitPointsDistance} from './camera-framing.js';
import {contextGroupFor} from './context-groups.js';
import {compilePathologyStates,resolvePathologyTarget} from './pathology-targets.js';
import {resolveOpacity} from './material-state.js';
import {sourceLaterality} from './laterality.js';
import {pathology,physiologicalMotion} from './pathology.js';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {organs,stateDefinitions} from './data.js';
export class AtlasScene{
 constructor(host,{onSelect,onHover,onProject,models}){
 this.pathologyStates={};this.restPoses=new WeakMap();this.motionPlaying=false;this.motionSpeed=1;this.motionTime=0;this.normalComparison=false;this.host=host;this.onProject=onProject;this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(35,1,.1,60);this.camera.position.set(3,2.6,7.8);
 this.renderer=new T.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));this.renderer.localClippingEnabled=true;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.setClearColor(0,0);this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;host.prepend(this.renderer.domElement);
 this.renderer.domElement.setAttribute('aria-label','선택한 장기의 3D 모델. 드래그 또는 방향키로 회전, 휠로 확대, 오른쪽 드래그로 이동');
 this.scene.add(new T.HemisphereLight('#fff7e7','#a9b8ad',2.0));const key=new T.DirectionalLight('#fff2dc',3.0);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=5;key.shadow.camera.bottom=-5;key.shadow.normalBias=.03;key.shadow.radius=4;this.scene.add(key);const fill=new T.DirectionalLight('#d9e7f1',1.5);fill.position.set(4,2,-3);this.scene.add(fill);
 this.stage=new T.Group();this.scene.add(this.stage);const mat=new T.MeshStandardMaterial({color:'#ddd9c9',roughness:.9});for(const [r,h,y] of [[1.93,.18,-1.8],[1.79,.25,-1.59],[1.72,.09,-1.42]]){const m=new T.Mesh(new T.CylinderGeometry(r,r,h,64),mat);m.position.y=y;m.receiveShadow=true;m.castShadow=true;this.stage.add(m)}
 const floor=new T.Mesh(new T.PlaneGeometry(200,200),new T.ShadowMaterial({opacity:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.92;floor.receiveShadow=true;this.scene.add(floor);
 this.models=models;for(const m of Object.values(this.models)){this.scene.add(m);m.visible=false}if(this.models.body)this.models.body.position.y=.8;
 this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.dirty=true;this.controls.addEventListener('change',()=>this.dirty=true);this.controls.enableDamping=true;this.controls.dampingFactor=.085;this.controls.minDistance=.4;this.controls.maxDistance=12;this.controls.minPolarAngle=.4;this.controls.maxPolarAngle=2.65;this.controls.target.set(0,.1,0);this.controls.addEventListener('start',()=>{this.resetting=false;this.focusTransition=null});
 this.renderer.domElement.tabIndex=0;
 this.renderer.domElement.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||e.altKey||e.ctrlKey||e.metaKey)return;e.preventDefault();this.rotateWithKey(e.key)});
 this.ray=new T.Raycaster();this.pointer=new T.Vector2();let down=null;const pointers=new Set();let multi=false;const hit=e=>{const r=host.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);this.lastHit=this.visibleHits(this.models[this.active])[0]?.object.userData;return this.lastHit?.organId};
 this.renderer.domElement.addEventListener('pointerdown',e=>{this.renderer.domElement.focus({preventScroll:true});pointers.add(e.pointerId);if(pointers.size>1)multi=true;down={x:e.clientX,y:e.clientY,id:e.pointerId}});
 this.renderer.domElement.addEventListener('pointerup',e=>{if(!multi&&down&&down.id===e.pointerId&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<6){const id=hit(e);if(id)onSelect(id,this.lastHit?.partId)}down=null;pointers.delete(e.pointerId);if(!pointers.size)multi=false});
 this.renderer.domElement.addEventListener('pointercancel',e=>{down=null;pointers.delete(e.pointerId);if(!pointers.size)multi=false});
 this.renderer.domElement.addEventListener('pointermove',e=>{if(pointers.size)return;const id=hit(e);if(this.hover!==id||this.hoverPart!==this.lastHit?.partId)this.dirty=true;this.hover=id;this.hoverPart=this.lastHit?.partId;host.style.cursor=id?'pointer':'grab';onHover(id,this.lastHit?.partId?selectionEnglishName({id:this.lastHit.partId,organId:this.lastHit.organId,detail:this.lastHit.detail}):null)});
 this.renderer.domElement.addEventListener('pointerleave',()=>{this.hover=null;this.hoverPart=null;this.dirty=true;onHover(null)});
 this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(host);this.effect={effect:'normal',intensity:.65};this.setView(Object.keys(models)[0]||'heart');this.last=performance.now();this.renderer.setAnimationLoop(t=>this.frame(t));
 }
 rotateWithKey(key){
 const target=this.controls.target.clone(),position=this.focusTransition?.position||this.camera.position;
 const spherical=new T.Spherical().setFromVector3(position.clone().sub(target)),step=Math.PI/36;
 if(key==='ArrowLeft')spherical.theta+=step;if(key==='ArrowRight')spherical.theta-=step;
 if(key==='ArrowUp')spherical.phi-=step;if(key==='ArrowDown')spherical.phi+=step;
 spherical.phi=T.MathUtils.clamp(spherical.phi,this.controls.minPolarAngle,this.controls.maxPolarAngle);
 const next=target.clone().add(new T.Vector3().setFromSpherical(spherical));
 this.resetting=false;this.focused=true;this.dirty=true;
 if(this.reduced){this.camera.position.copy(next);this.controls.update();this.focusTransition=null}else this.focusTransition={target,position:next};
 }
 replaceModel(id,model){const previous=this.models[id];if(previous===model)return;if(previous){this.scene.remove(previous);disposeDetailModel(previous)}this.models[id]=model;this.scene.add(model);model.visible=false;}
 addModel(id,model){if(!this.models[id]){this.models[id]=model;this.scene.add(model);model.visible=false;}}
 setOverviewFilter(system){const body=this.models.body;if(body)body.children.forEach(g=>g.visible=g.userData.isShell||!system||g.userData.system===system);this.dirty=true;}


 setPathology(state){const context=this.models[this.active]?.userData.context?contextGroupFor(this.active):null;const id=this.active==='body'||context?.members.includes(state.organId)?state.organId:this.active;if(!pathology[id])return;const scenario=pathology[id].find(p=>p.id===state.id);delete this.pathologyStates[id];this.pathologyStates[id]={id:scenario?.id||null,side:['L','R'].includes(state.side)?state.side:null,partId:typeof state.partId==='string'&&scenario&&new RegExp(scenario.target).test(state.partId)?state.partId:null,intensity:Math.min(1,Math.max(0,Number(state.intensity)||0))};this.dirty=true;this.transitionUntil=performance.now()+500;}
 setMotion(playing,speed=1){this.motionPlaying=!!playing;this.motionSpeed=Math.min(2,Math.max(.25,speed));this.dirty=true;}
 applyPathology(dt){if(this.motionPlaying)this.motionTime+=dt*this.motionSpeed;const root=this.models[this.active];const candidates=compilePathologyStates(this.pathologyStates,this.normalComparison);let affected=0;root.traverse(m=>{if(!m.isMesh||!m.userData.partId)return;let pose=this.restPoses.get(m);if(!pose){m.geometry.computeBoundingBox();pose={position:m.position.clone(),scale:m.scale.clone(),rotation:m.quaternion.clone(),center:m.geometry.boundingBox.getCenter(new T.Vector3())};this.restPoses.set(m,pose);}const organ=m.userData.organId,resolved=resolvePathologyTarget(m.userData.partId,candidates),stored=resolved?.state,scenario=resolved?.scenario,hit=!!resolved;let pathologicalOpacity=null;let size=1;if(hit){affected++;const intensity=stored.intensity;m.material.color.lerp(new T.Color(scenario.color),intensity*.8);if(scenario.kind==='expand')size+=scenario.amount*intensity;if(scenario.kind==='opacity'){const base=m.userData.restOpacity??1;pathologicalOpacity=base+(scenario.amount-base)*intensity;}if(this.motionPlaying){m.material.emissive.set(scenario.color);m.material.emissiveIntensity=.04+Math.sin(this.motionTime*2)*.025;}}
 const previous=pose.pathologyScale??1;pose.pathologyScale=this.reduced?size:previous+(size-previous)*(1-Math.exp(-16*Math.max(0,dt)));if(Math.abs(size-pose.pathologyScale)<.0001)pose.pathologyScale=size;else this.dirty=true;size=pose.pathologyScale;
 // Pausing freezes the phase. Recompute from that same phase on redraws so
 // selection, camera movement, and normal comparison do not reset the pose.
 const motion=physiologicalMotion[organ];if(motion&&new RegExp(motion.target).test(m.userData.partId)){const factor=scenario?.id==='dilated'?.35:1;size+=Math.sin(this.motionTime*Math.PI*2*motion.frequency)*motion.amplitude*factor;}
 m.scale.copy(pose.scale).multiplyScalar(size);m.position.copy(pose.position).add(pose.center.clone().multiply(pose.scale).multiplyScalar(1-size).applyQuaternion(pose.rotation));if(m.userData.explodeOffset)m.position.addScaledVector(m.userData.explodeOffset,this.explodeAmount||0);
 if(!(organ==='skin'&&this.active==='body')){m.material.opacity=resolveOpacity({restOpacity:m.userData.restOpacity,selected:m.userData.inspectionSelected,ghost:m.userData.inspectionGhost,pathologyOpacity:pathologicalOpacity});const selectedTop=!!m.userData.inspectionSelected&&this.inspection?.mode==='context';m.material.transparent=m.material.opacity<1||selectedTop;m.material.depthWrite=selectedTop||!m.material.transparent;m.renderOrder=selectedTop?10:0;}
 });this.host.dataset.pathologyParts=affected;this.host.dataset.motion=this.motionPlaying?'playing':'paused';}
 visibleHits(model){return this.ray.intersectObject(model,true).filter(h=>{for(let o=h.object;o;o=o.parent)if(!o.visible)return false;return !(h.object.material.clippingPlanes||[]).some(p=>p.distanceToPoint(h.point)<0);});}
 getParts(){const parts=[];this.models[this.active]?.traverse(m=>{if(m.isMesh&&m.userData.partId)parts.push({id:m.userData.partId,label:m.userData.label,organId:m.userData.organId,detail:m.userData.detail||null})});return parts;}
 inspect(options){
 this.inspection={...this.inspection,...options};const q=this.inspection,model=this.models[this.active];if(!model)return;model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model),axis=({coronal:'z',sagittal:'x',axial:'y'})[q.slicePlane]||'z';const normal=new T.Vector3();normal[axis]=-1;const position=T.MathUtils.lerp(box.min[axis],box.max[axis],T.MathUtils.clamp(q.cut/100,0,1));const plane=new T.Plane(normal,position);let visible=0;
 model.traverse(m=>{if(!m.isMesh||!m.userData.partId||(m.userData.organId==='skin'&&this.active==='body'))return;const id=m.userData.partId;const match=(!q.organ||!!getStructureIdentity(q.organ,id))&&(!q.part||id===q.part)&&(!q.route||new RegExp(q.route).test(id))&&(!q.side||sourceLaterality(id)===q.side);m.visible=(!this.baseSide||sourceLaterality(id)===this.baseSide)&&(q.mode!=='isolate'||match);if(m.visible)visible++;m.userData.inspectionSelected=match&&!!(q.organ||q.part||q.route||q.side);const ghost=q.mode==='context'&&!match;m.userData.inspectionGhost=ghost;m.userData.restCastShadow??=m.castShadow;m.castShadow=ghost?false:m.userData.restCastShadow;m.material.opacity=ghost ? Math.min(.4,m.userData.restOpacity??1) : ((match&&(q.organ||q.part||q.route||q.side)) ? 1 : (m.userData.restOpacity??1));const selectedTop=!!m.userData.inspectionSelected&&this.inspection?.mode==='context';m.material.transparent=m.material.opacity<1||selectedTop;m.material.depthWrite=selectedTop||!m.material.transparent;m.renderOrder=selectedTop?10:0;m.material.clippingPlanes=q.slice?[plane]:[];const side=q.slice||m.userData.inspectionSelected?T.DoubleSide:T.FrontSide;m.material.forceSinglePass=true;if(m.material.side!==side){m.material.side=side;m.material.needsUpdate=true;}});this.host.dataset.visibleParts=visible;this.host.dataset.part=q.part;this.dirty=true;this.transitionUntil=performance.now()+500;
 }
 focusPart(){const box=new T.Box3();this.models[this.active].traverse(m=>{if(m.isMesh&&m.visible&&m.userData.inspectionSelected)box.expandByObject(m)});if(box.isEmpty())return;const center=box.getCenter(new T.Vector3()),radius=box.getSize(new T.Vector3()).length()/2;const direction=this.camera.position.clone().sub(this.controls.target).normalize();const distance=focusDistance(radius,this.camera.fov,this.camera.aspect);this.controls.maxDistance=Math.max(12,distance*1.1);this.focusTransition={target:center,position:center.clone().addScaledVector(direction,distance)};if(this.reduced){this.controls.target.copy(this.focusTransition.target);this.camera.position.copy(this.focusTransition.position);this.focusTransition=null;}this.resetting=false;this.focused=true;this.dirty=true;}
 setExplode(amount){
 const root=this.models[this.active];if(!root||this.active==='body')return;
 const groups=prepareGroupedExplosion(root);this.host.dataset.explodeGroups=String(groups.length);
 const next=Math.max(0,Math.min(1,amount));
 if(next>0){
  const cameraPose=this.focusTransition||{target:this.controls.target,position:this.camera.position};
  if(!this.explosionCamera)this.explosionCamera={target:cameraPose.target.clone(),position:cameraPose.position.clone()};
  root.updateMatrixWorld(true);const box=new T.Box3(),origin=new T.Vector3(),assemblyBoxes=[];
  root.traverse(m=>{if(!m.isMesh||!m.visible||m.userData.contextStructure)return;const bounds=new T.Box3().setFromObject(m);if(m.userData.explodeOffset){const delta=m.userData.explodeOffset.clone().multiplyScalar(next-(this.explodeAmount||0));origin.set(0,0,0).applyMatrix4(m.parent.matrixWorld);delta.applyMatrix4(m.parent.matrixWorld).sub(origin);bounds.translate(delta)}box.union(bounds);assemblyBoxes.push(bounds)});
  if(!box.isEmpty()){const target=box.getCenter(new T.Vector3()),direction=cameraPose.position.clone().sub(cameraPose.target).normalize(),right=new T.Vector3().crossVectors(this.camera.up,direction).normalize(),up=new T.Vector3().crossVectors(direction,right).normalize(),points=[];for(const bounds of assemblyBoxes)for(const x of [bounds.min.x,bounds.max.x])for(const y of [bounds.min.y,bounds.max.y])for(const z of [bounds.min.z,bounds.max.z]){const v=new T.Vector3(x,y,z).sub(target);points.push([v.dot(right),v.dot(up),v.dot(direction)])}const distance=fitPointsDistance(points,this.camera.fov,this.camera.aspect,1.25);this.controls.maxDistance=Math.max(12,distance*1.1);this.focusTransition={target,position:target.clone().addScaledVector(direction,distance)};this.focused=true;}
 }else if(this.explosionCamera){this.focusTransition=this.explosionCamera;this.explosionCamera=null;this.focused=false;}
 if(this.reduced&&this.focusTransition){this.controls.target.copy(this.focusTransition.target);this.camera.position.copy(this.focusTransition.position);this.focusTransition=null;}
 this.explodeTarget=next;this.dirty=true;this.transitionUntil=performance.now()+1000;
 }
 setSide(side){this.baseSide=side;this.inspect({part:'',route:'',side:'',mode:'all'});if(side){const box=new T.Box3();this.models[this.active].traverse(m=>{if(m.isMesh&&m.visible)box.expandByObject(m)});if(!box.isEmpty()){const center=box.getCenter(new T.Vector3()),distance=focusDistance(box.getSize(new T.Vector3()).length()/2,this.camera.fov,this.camera.aspect,.95);this.focusTransition={target:center,position:center.clone().add(new T.Vector3(0,.15,1).normalize().multiplyScalar(distance))};this.focused=true;if(this.reduced){this.controls.target.copy(center);this.camera.position.copy(this.focusTransition.position);this.focusTransition=null;}}}else this.reset();}
 resize(){const {width,height}=this.host.getBoundingClientRect();this.dirty=true;this.renderer.setSize(width,height);this.camera.aspect=width/height;this.camera.updateProjectionMatrix();if(this.explodeTarget>0)this.setExplode(this.explodeTarget)}
 setView(id){const nextModel=this.models[id];if(this.motionModel!==nextModel&&(this.motionModel?.userData.detail?.motionSequence||nextModel?.userData.detail?.motionSequence)){this.motionPlaying=false;this.motionTime=0;}this.motionModel=nextModel;delete this.host.dataset.detailMotionStep;this.explosionCamera=null;this.explodeTarget=0;this.explodeAmount=0;this.baseSide=['eyes','kidneys','ovaries','knees','tonsils','adrenals','testes'].includes(id)?'L':'';this.focused=false;this.inspection={part:'',organ:'',mode:'all',route:'',slice:false,slicePlane:'coronal',cut:50,side:''};this.dirty=true;this.active=id;this.progress=0;for(const [key,m]of Object.entries(this.models))m.visible=key===id;this.reset()}
 reset(){this.controls.maxDistance=12;this.focused=false;this.resetting=false;this.dirty=true;const body=this.active==='body';this.focusTransition={target:new T.Vector3(0,body?.8:.1,0),position:new T.Vector3(body?2.6:2.2,body?2.1:1.7,body?10.3:6)};if(this.reduced){this.controls.target.copy(this.focusTransition.target);this.camera.position.copy(this.focusTransition.position);this.focusTransition=null;}if(this.explodeTarget>0)this.setExplode(this.explodeTarget)}
 setAngle(angle){this.focusTransition=null;this.focused=false;this.resetting=false;const vectors={front:[0,.8,9],side:[9,.8,0],back:[0,.8,-9],bottom:[0,-7,6]};this.camera.position.set(...vectors[angle]);this.controls.target.set(0,.15,0);this.controls.update();if(this.explodeTarget>0)this.setExplode(this.explodeTarget)}
 setState(state){this.effect={...state};this.dirty=true;this.transitionUntil=performance.now()+500}
 zoom(factor){this.focusTransition=null;this.dirty=true;this.camera.position.sub(this.controls.target).multiplyScalar(factor).clampLength(this.controls.minDistance,this.controls.maxDistance).add(this.controls.target);this.resetting=false}
 advanceFocus(dt){if(!this.focusTransition)return;const f=this.focusTransition,alpha=1-Math.exp(-12*dt);this.controls.target.lerp(f.target,alpha);this.camera.position.lerp(f.position,alpha);this.dirty=true;if(this.controls.target.distanceTo(f.target)<.001&&this.camera.position.distanceTo(f.position)<.001){this.controls.target.copy(f.target);this.camera.position.copy(f.position);this.focusTransition=null;}}
 frame(now){const dt=Math.min((now-this.last)/1000,.05);this.last=now;this.progress=Math.min(1,this.progress+dt/ .5);const ease=this.reduced?1:1-Math.pow(1-this.progress,3);
 if(this.resetting){this.camera.position.lerp(new T.Vector3(this.active==='body'?2.6:3,this.active==='body'?2.1:2.6,this.active==='body'?10.3:7.8),this.reduced?1:.12);if(this.camera.position.distanceTo(new T.Vector3(this.active==='body'?2.6:3,this.active==='body'?2.1:2.6,this.active==='body'?10.3:7.8))<.01)this.resetting=false}
 const target=this.explodeTarget||0;this.explodeAmount=this.reduced?target:(this.explodeAmount||0)+(target-(this.explodeAmount||0))*(1-Math.exp(-10*dt));if(Math.abs(this.explodeAmount-target)>.001)this.dirty=true;else this.explodeAmount=target;this.advanceFocus(dt);if(!this.focused)this.controls.target.clamp(new T.Vector3(-.8,-.6,-.5),new T.Vector3(.8,1.2,.5));this.controls.update();if(!this.motionPlaying&&!this.dirty&&!this.resetting&&now>(this.transitionUntil||0)&&this.progress>=1&&(this.effect.effect==='normal'||this.reduced))return;this.dirty=false;this.stage.visible=!this.focused&&this.camera.position.y>-.3;const model=this.models[this.active];const state=stateDefinitions[this.effect.effect];const intensity=this.effect.intensity;const pulse=this.reduced?0:Math.sin(now*.0028)*state.pulse*intensity;const scale=this.active==='body'?1:1+(state.scale-1)*intensity+pulse;model.scale.setScalar(scale*(.86+.14*ease));model.position.y=(this.active==='body'?.8:0)+(1-ease)*-.15;
 model.traverse(m=>{if(!m.isMesh||!m.userData.baseColor)return;const target=m.userData.baseColor.clone();if(m.userData.inspectionGhost)target.lerp(new T.Color('#cdd5ce'),.7);if(this.active!=='body'&&state.tint)target.lerp(new T.Color(state.tint),intensity*.7);this.reduced?m.material.color.copy(target):m.material.color.lerp(target,.18);m.material.emissive.set(m.userData.inspectionSelected?'#58766a':m.userData.partId===this.hoverPart?'#66584b':'#000000');m.material.emissiveIntensity=m.userData.inspectionSelected?.22:this.hover?.09:0});
 this.applyPathology(dt);const sequence=model.userData.detail?.motionSequence;if(sequence){const step=sequence[Math.floor(this.motionTime/1.4)%sequence.length];this.host.dataset.detailMotionStep=step.label;if(this.motionPlaying||this.motionTime>0)model.traverse(m=>{if(m.isMesh&&!m.userData.inspectionSelected&&step.parts.some(id=>m.userData.partId?.endsWith(':'+id))){m.material.emissive.set('#ad8032');m.material.emissiveIntensity=.5;}})}else delete this.host.dataset.detailMotionStep;this.scene.updateMatrixWorld();this.camera.updateMatrixWorld();const selectedBox=new T.Box3();model.traverse(m=>{if(m.isMesh&&m.visible&&m.userData.inspectionSelected)selectedBox.expandByObject(m)});let p=(selectedBox.isEmpty()?new T.Vector3(0,0,0).applyMatrix4(model.matrixWorld):selectedBox.getCenter(new T.Vector3())).project(this.camera);this.onProject({x:(p.x+1)/2*this.host.clientWidth,y:(1-p.y)/2*this.host.clientHeight,visible:Math.abs(p.x)<1&&Math.abs(p.y)<1&&p.z<1});this.renderer.render(this.scene,this.camera);this.host.dataset.renderedFrames=String(Number(this.host.dataset.renderedFrames||0)+1);this.host.dataset.geometryCount=this.renderer.info.memory.geometries;this.host.dataset.drawCalls=this.renderer.info.render.calls;this.host.dataset.triangles=this.renderer.info.render.triangles;this.host.dataset.explode=String(this.explodeAmount||0);
 }
 dispose(){if(this.disposed)return;this.disposed=true;this.renderer.setAnimationLoop(null);this.observer.disconnect();this.controls.dispose();const geometries=new Set(),materials=new Set();this.scene.traverse(m=>{if(m.geometry)geometries.add(m.geometry);if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(x=>materials.add(x))});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());this.renderer.dispose();this.renderer.forceContextLoss();this.renderer.domElement.remove()}
}


