"use client";

import Link from "next/link";
import { useDeferredValue, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowUpRight, Bug, BookOpenCheck, Filter, FlaskConical, Pill, Search, ShieldAlert, Stethoscope } from "lucide-react";
import type { AntibioticSpectrumDataset } from "@/lib/types";
import type { InfectionPathway, InfectionPathwayDataset, InfectionPopulation, InfectionSetting, PathogenLikelihood, RegimenRank } from "@/lib/infection-types";
import { ClinicalInfectionQuiz } from "@/components/clinical-infection-quiz";

type ViewMode = "explore" | "quiz";
const SETTING_LABELS: Record<InfectionSetting, string> = { community: "지역사회", mixed: "상황별", "healthcare-associated": "의료 관련", "hospital-acquired": "병원 획득", "ventilator-associated": "인공호흡기 관련", "procedure-associated": "시술·기기 관련" };
const POPULATION_LABELS: Record<InfectionPopulation, string> = { adult: "성인", pediatric: "소아", neonate: "신생아", pregnant: "임신", immunocompromised: "면역저하", neutropenic: "호중구감소" };
const LIKELIHOOD_LABELS: Record<PathogenLikelihood, string> = { common: "흔함", important: "중요", "risk-factor-dependent": "위험인자 의존", uncommon: "드묾", excluded: "배제" };
const RANK_LABELS: Record<RegimenRank, string> = { preferred: "우선 고려", alternative: "대안", conditional: "조건부", salvage: "구제요법", "not-recommended": "비권장" };
const SITE_LABELS: Record<string, string> = { "lower-respiratory-tract": "하기도", "lower-urinary-tract": "하부 요로", "upper-urinary-tract": "상부 요로", "skin-soft-tissue": "피부·연조직", systemic: "전신", endovascular: "심혈관·혈류", "central-nervous-system": "중추신경계", "bone-spine": "골·척추", "bloodstream-catheter": "도관·혈류", peritoneal: "복막" };

function normalize(value: string) { return value.toLocaleLowerCase().replace(/[\s/_-]+/g, ""); }
function unique<T>(items: T[]) { return [...new Set(items)]; }

function RegimenCard({ regimen, spectrum }: { regimen: InfectionPathway["empiricRegimens"][number]; spectrum: AntibioticSpectrumDataset }) {
  return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-slate-950">{regimen.context}</strong><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${regimen.rank === "preferred" ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-900"}`}>{RANK_LABELS[regimen.rank]}</span></div><div className="mt-3 space-y-2">{regimen.components.map((component, index) => <div key={`${regimen.id}-${index}`} className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold uppercase text-slate-400">{index > 0 ? (component.selection === "optional" ? "필요 시 추가" : "AND") : component.selection === "one-of" ? "하나 선택" : "기본"}</span>{component.antibioticIds.map((id) => { const drug = spectrum.antibiotics.find((item) => item.id === id); return drug ? <Link key={id} href={`/drugs/antibiotics?mode=antibiotic&antibiotic=${id}`} className="rounded-full border border-teal-200 bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-900 hover:border-teal-500">{drug.inn}</Link> : null; })}</div>)}</div>{regimen.conditions.length ? <ul className="mt-4 space-y-1 text-xs leading-5 text-slate-700">{regimen.conditions.map((item) => <li key={item}>• {item}</li>)}</ul> : null}{regimen.avoidWhen.length ? <div className="mt-3 rounded-lg bg-rose-50 p-3 text-xs leading-5 text-rose-900"><strong>피하거나 재평가:</strong> {regimen.avoidWhen.join(" · ")}</div> : null}{regimen.notes.map((item) => <p key={item} className="mt-2 text-xs leading-5 text-slate-600">{item}</p>)}</article>;
}

export function InfectionPathwayExplorer({ dataset, spectrum, initialPathway = "", initialOrganism = "", initialAntibiotic = "" }: { dataset: InfectionPathwayDataset; spectrum: AntibioticSpectrumDataset; initialPathway?: string; initialOrganism?: string; initialAntibiotic?: string }) {
  const searchParams = useSearchParams();
  const verified = dataset.pathways.filter((item) => item.reviewStatus === "verified");
  const resolvedPathway = initialPathway || searchParams.get("pathway") || "";
  const resolvedOrganism = initialOrganism || searchParams.get("organism") || "";
  const resolvedAntibiotic = initialAntibiotic || searchParams.get("antibiotic") || "";
  const [mode, setMode] = useState<ViewMode>("explore");
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const [site, setSite] = useState("");
  const [setting, setSetting] = useState("");
  const [population, setPopulation] = useState("");
  const [organismFilter] = useState(resolvedOrganism);
  const [antibioticFilter] = useState(resolvedAntibiotic);
  const [selectedId, setSelectedId] = useState(resolvedPathway || verified.find((item) => resolvedOrganism ? item.pathogenGroups.some((group) => group.organisms.some((organism) => organism.organismId === resolvedOrganism)) : resolvedAntibiotic ? item.empiricRegimens.some((regimen) => regimen.components.some((component) => component.antibioticIds.includes(resolvedAntibiotic))) || item.targetedTherapies.some((therapy) => therapy.antibioticIds.includes(resolvedAntibiotic)) : false)?.id || verified[0]?.id || "");
  const sites = unique(verified.map((item) => item.infectionSite));
  const filtered = verified.filter((item) => {
    const searchable = normalize([item.displayName, item.diseaseTitle, ...item.aliases].join(" "));
    return (!deferredQuery || searchable.includes(normalize(deferredQuery))) && (!site || item.infectionSite === site) && (!setting || item.setting === setting || item.setting === "mixed") && (!population || item.population.includes(population as InfectionPopulation)) && (!organismFilter || item.pathogenGroups.some((group) => group.organisms.some((organism) => organism.organismId === organismFilter))) && (!antibioticFilter || item.empiricRegimens.some((regimen) => regimen.components.some((component) => component.antibioticIds.includes(antibioticFilter))) || item.targetedTherapies.some((therapy) => therapy.antibioticIds.includes(antibioticFilter)));
  });
  const selected = verified.find((item) => item.id === selectedId) ?? filtered[0];
  const selectPathway = (id: string) => { setSelectedId(id); const url = new URL(window.location.href); url.searchParams.set("pathway", id); window.history.replaceState(null, "", url); };
  const reset = () => { setQuery(""); setSite(""); setSetting(""); setPopulation(""); };

  return <div className="space-y-3">
    <div className="flex flex-wrap items-center justify-between gap-3">
      <div className="inline-flex rounded-full border border-slate-200 bg-white p-1 shadow-sm"><button type="button" onClick={() => setMode("explore")} className={`rounded-full px-3 py-1.5 text-xs font-bold sm:px-4 sm:text-sm ${mode === "explore" ? "bg-slate-950 text-white" : "text-slate-600"}`}>{"\uc784\uc0c1 \uacbd\ub85c \ud0d0\uc0c9"}</button><button type="button" onClick={() => setMode("quiz")} className={`rounded-full px-3 py-1.5 text-xs font-bold sm:px-4 sm:text-sm ${mode === "quiz" ? "bg-teal-700 text-white" : "text-slate-600"}`}>{"\ud034\uc988"}</button></div>
      {mode === "explore" ? <span className="text-xs text-slate-500">{"\uac80\uc99d\ub41c \uacbd\ub85c"} {filtered.length}/{verified.length}{"\uac1c"}</span> : null}
    </div>
    {mode === "quiz" ? <ClinicalInfectionQuiz pathways={verified} spectrum={spectrum} sources={dataset.sources} /> : <>
      <div className="grid gap-4 xl:grid-cols-[280px_minmax(0,1fr)]">
        <aside className="space-y-3 xl:sticky xl:top-4 xl:self-start">
          <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><div className="space-y-2"><label className="relative block"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><span className="sr-only">{"\uc9c8\ud658 \uac80\uc0c9"}</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={"\uc9c8\ud658\uba85 \uac80\uc0c9"} className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-3 text-sm focus:border-teal-500 focus:outline-none" /></label><div className="grid grid-cols-2 gap-2"><select value={site} onChange={(event) => setSite(event.target.value)} className="min-w-0 rounded-xl border border-slate-200 px-2 py-2 text-xs"><option value="">{"\ubaa8\ub4e0 \uac10\uc5fc \ubd80\uc704"}</option>{sites.map((item) => <option key={item} value={item}>{SITE_LABELS[item] ?? item}</option>)}</select><select value={setting} onChange={(event) => setSetting(event.target.value)} className="min-w-0 rounded-xl border border-slate-200 px-2 py-2 text-xs"><option value="">{"\ubaa8\ub4e0 \uac10\uc5fc \ud658\uacbd"}</option>{Object.entries(SETTING_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="flex items-center justify-between gap-2"><select value={population} onChange={(event) => setPopulation(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-2 py-2 text-xs"><option value="">{"\ubaa8\ub4e0 \ub300\uc0c1\uad70"}</option>{Object.entries(POPULATION_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={reset} className="inline-flex items-center justify-center gap-1 rounded-xl border border-slate-200 px-2.5 py-2 text-xs text-slate-600"><Filter className="h-3.5 w-3.5" />{"\ucd08\uae30\ud654"}</button></div></div></section>
          <div className="space-y-2 xl:max-h-[66vh] xl:overflow-auto xl:pr-1">{filtered.map((item) => <button key={item.id} type="button" onClick={() => selectPathway(item.id)} className={`w-full rounded-xl border p-3 text-left transition ${selected?.id === item.id ? "border-teal-600 bg-teal-50 shadow-sm" : "border-slate-200 bg-white hover:border-teal-300"}`}><strong className="block text-sm text-slate-950">{item.displayName}</strong><span className="mt-1 block text-xs text-slate-500">{SITE_LABELS[item.infectionSite] ?? item.infectionSite} {"\u00b7"} {SETTING_LABELS[item.setting]}</span></button>)}{filtered.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">{"\uc870\uac74\uc5d0 \ub9de\ub294 \uac80\uc99d \uacbd\ub85c\uac00 \uc5c6\uc2b5\ub2c8\ub2e4."}</div> : null}</div>
        </aside>
      {selected ? <main className="order-first space-y-4 xl:order-none"><header className="rounded-2xl bg-slate-950 p-5 text-white shadow-sm sm:p-7"><div className="flex flex-wrap items-center gap-2 text-xs text-teal-300"><BookOpenCheck className="h-4 w-4" />Verified · {selected.reviewedAt}</div><h1 className="mt-3 text-2xl font-bold sm:text-3xl">{selected.displayName}</h1><div className="mt-4 flex flex-wrap gap-2">{selected.population.map((item) => <span key={item} className="rounded-full bg-white/10 px-3 py-1 text-xs">{POPULATION_LABELS[item]}</span>)}{selected.severity.map((item) => <span key={item} className="rounded-full bg-white/10 px-3 py-1 text-xs">{item}</span>)}</div><Link href={`/disease/${selected.diseaseSlug}`} className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-teal-200 hover:text-white">기존 질환 노트 <ArrowUpRight className="h-4 w-4" /></Link></header>
      <section className="grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-sm font-bold"><FlaskConical className="h-4 w-4 text-teal-700" />진단·배양</div><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{selected.diagnosticNotes.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-sm font-bold"><Stethoscope className="h-4 w-4 text-teal-700" />Source control·stewardship</div><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{[...selected.sourceControlNotes, ...selected.stewardshipNotes].map((item) => <li key={item}>• {item}</li>)}</ul></div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex items-center gap-2 text-sm font-bold"><Bug className="h-4 w-4 text-teal-700" />예상 원인균</div><div className="mt-4 space-y-4">{selected.pathogenGroups.map((group) => <div key={group.context}><h3 className="text-xs font-bold uppercase tracking-wide text-slate-500">{group.context}</h3><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{group.organisms.map((item) => { const organism = spectrum.organisms.find((entry) => entry.id === item.organismId); return organism ? <article key={item.organismId} className="rounded-lg border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{organism.label}</strong><span className="text-[11px] text-teal-700">{LIKELIHOOD_LABELS[item.likelihood]}</span></div>{item.notes[0] ? <p className="mt-2 text-xs leading-5 text-slate-600">{item.notes[0]}</p> : null}<div className="mt-3 flex flex-wrap gap-2">{organism.noteSlug ? <Link href={`/disease/${organism.noteSlug}`} className="text-xs font-semibold text-teal-800 hover:underline">병원체 노트</Link> : null}<Link href={`/drugs/antibiotics?mode=organism&organism=${item.organismId}`} className="text-xs font-semibold text-slate-600 hover:text-teal-800">spectrum 보기</Link></div></article> : null; })}</div></div>)}</div></section>
      <section><div className="mb-3 flex items-center gap-2 text-sm font-bold"><Pill className="h-4 w-4 text-teal-700" />경험적 항균요법</div>{selected.empiricRegimens.length ? <div className="grid gap-3 lg:grid-cols-2">{selected.empiricRegimens.map((item) => <RegimenCard key={item.id} regimen={item} spectrum={spectrum} />)}</div> : <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><ShieldAlert className="mr-2 inline h-4 w-4" />이 질환은 고정된 단일 경험요법으로 제시하지 않습니다. 배양, 감염 환경과 전문팀 판단을 우선합니다.</div>}</section>
      {selected.targetedTherapies.length ? <section><div className="mb-3 text-sm font-bold">배양 후 표적치료 예시</div><div className="grid gap-3 md:grid-cols-2">{selected.targetedTherapies.map((therapy, index) => { const organism = spectrum.organisms.find((item) => item.id === therapy.organismId); return <article key={`${therapy.organismId}-${index}`} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-sm">{organism?.label ?? therapy.organismId}</strong><p className="mt-1 text-xs text-slate-500">{therapy.susceptibilityCondition}</p><div className="mt-3 flex flex-wrap gap-2">{therapy.antibioticIds.map((id) => { const drug = spectrum.antibiotics.find((item) => item.id === id); return drug ? <Link key={id} href={`/drugs/antibiotics?mode=antibiotic&antibiotic=${id}`} className="rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-900">{drug.inn}</Link> : null; })}</div>{therapy.notes.map((item) => <p key={item} className="mt-2 text-xs leading-5 text-slate-600">{item}</p>)}</article>; })}</div></section> : null}
      <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">근거</div><div className="mt-3 flex flex-wrap gap-2">{selected.sourceIds.map((id) => { const source = dataset.sources.find((item) => item.id === id); return source ? <a key={id} href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs text-teal-800 hover:border-teal-400">{source.label} ({source.year})<ArrowUpRight className="h-3 w-3" /></a> : null; })}</div></section>
      </main> : null}</div>
    </>}
    <footer className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-600"><strong className="text-slate-800">해석 주의:</strong> {dataset.disclaimer} · 전체 검토일 {dataset.reviewedAt}</footer>
  </div>;
}
