"use client";

import Link from "next/link";
import { useDeferredValue, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowUpRight, Bug, BookOpenCheck, Filter, FlaskConical, Pill, Search, ShieldAlert, Stethoscope } from "lucide-react";
import type { AntibioticSpectrumDataset } from "@/lib/types";
import type { InfectionPathway, InfectionPathwayDataset, InfectionPopulation, InfectionSetting, PathogenLikelihood, RegimenRank } from "@/lib/infection-types";

const SETTING_LABELS: Record<InfectionSetting, string> = { community: "지역사회", mixed: "상황별", "healthcare-associated": "의료 관련", "hospital-acquired": "병원 획득", "ventilator-associated": "인공호흡기 관련", "procedure-associated": "시술·기기 관련" };
const POPULATION_LABELS: Record<InfectionPopulation, string> = { adult: "성인", pediatric: "소아", neonate: "신생아", pregnant: "임신", immunocompromised: "면역저하", neutropenic: "호중구감소" };
const LIKELIHOOD_LABELS: Record<PathogenLikelihood, string> = { common: "흔함", important: "중요", "risk-factor-dependent": "위험인자 의존", uncommon: "드묾", excluded: "배제" };
const RANK_LABELS: Record<RegimenRank, string> = { preferred: "우선 고려", alternative: "대안", conditional: "조건부", salvage: "구제요법", "not-recommended": "비권장" };
const SITE_LABELS: Record<string, string> = { "lower-respiratory-tract": "하기도", "lower-urinary-tract": "하부 요로", "upper-urinary-tract": "상부 요로", "skin-soft-tissue": "피부·연조직", systemic: "전신", endovascular: "심혈관·혈류", "central-nervous-system": "중추신경계", "bone-spine": "골·척추", "bloodstream-catheter": "도관·혈류", peritoneal: "복막" };

function normalize(value: string) { return value.toLocaleLowerCase().replace(/[\s/_-]+/g, ""); }
function unique<T>(items: T[]) { return [...new Set(items)]; }

function RegimenCard({ regimen, spectrum }: { regimen: InfectionPathway["empiricRegimens"][number]; spectrum: AntibioticSpectrumDataset }) {
  return <article className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm text-slate-950">{regimen.context}</strong><span className={`rounded-full px-2.5 py-1 text-[11px] font-bold ${regimen.rank === "preferred" ? "bg-emerald-100 text-emerald-900" : "bg-amber-100 text-amber-900"}`}>{RANK_LABELS[regimen.rank]}</span></div><div className="mt-3 space-y-2">{regimen.components.map((component, index) => <div key={`${regimen.id}-${index}`} className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold uppercase text-slate-400">{index > 0 ? (component.selection === "optional" ? "필요 시 추가" : "AND") : component.selection === "one-of" ? "하나 선택" : "기본"}</span>{component.antibioticIds.map((id) => { const drug = spectrum.antibiotics.find((item) => item.id === id); return drug ? <Link key={id} href={`?view=antibiotics&mode=antibiotic&antibiotic=${id}`} className="rounded-full border border-teal-200 bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-900 hover:border-teal-500">{drug.inn}</Link> : null; })}</div>)}</div>{regimen.conditions.length ? <ul className="mt-4 space-y-1 text-xs leading-5 text-slate-700">{regimen.conditions.map((item) => <li key={item}>• {item}</li>)}</ul> : null}{regimen.avoidWhen.length ? <div className="mt-3 rounded-lg bg-rose-50 p-3 text-xs leading-5 text-rose-900"><strong>피하거나 재평가:</strong> {regimen.avoidWhen.join(" · ")}</div> : null}{regimen.notes.map((item) => <p key={item} className="mt-2 text-xs leading-5 text-slate-600">{item}</p>)}</article>;
}

export function InfectionPathwayExplorer({ dataset, spectrum, initialPathway = "", initialOrganism = "", initialAntibiotic = "" }: { dataset: InfectionPathwayDataset; spectrum: AntibioticSpectrumDataset; initialPathway?: string; initialOrganism?: string; initialAntibiotic?: string }) {
  const searchParams = useSearchParams();
  const clinicalPathways = dataset.pathways.filter((item) => item.reviewStatus === "verified" || item.reviewStatus === "reviewed");
  const resolvedPathway = initialPathway || searchParams.get("pathway") || "";
  const resolvedOrganism = initialOrganism || searchParams.get("organism") || "";
  const resolvedAntibiotic = initialAntibiotic || searchParams.get("antibiotic") || "";
  const [query, setQuery] = useState("");
  const deferredQuery = useDeferredValue(query);
  const [site, setSite] = useState("");
  const [setting, setSetting] = useState("");
  const [population, setPopulation] = useState("");
  const [organismFilter] = useState(resolvedOrganism);
  const [antibioticFilter] = useState(resolvedAntibiotic);
  const [selectedId, setSelectedId] = useState(resolvedPathway || clinicalPathways.find((item) => resolvedOrganism ? item.pathogenGroups.some((group) => group.organisms.some((organism) => organism.organismId === resolvedOrganism)) : resolvedAntibiotic ? item.empiricRegimens.some((regimen) => regimen.components.some((component) => component.antibioticIds.includes(resolvedAntibiotic))) || item.targetedTherapies.some((therapy) => therapy.antibioticIds.includes(resolvedAntibiotic)) : false)?.id || clinicalPathways[0]?.id || "");
  const sites = unique(clinicalPathways.map((item) => item.infectionSite));
  const filtered = clinicalPathways.filter((item) => {
    const searchable = normalize([item.displayName, item.diseaseTitle, ...item.aliases].join(" "));
    return (!deferredQuery || searchable.includes(normalize(deferredQuery))) && (!site || item.infectionSite === site) && (!setting || item.setting === setting || item.setting === "mixed") && (!population || item.population.includes(population as InfectionPopulation)) && (!organismFilter || item.pathogenGroups.some((group) => group.organisms.some((organism) => organism.organismId === organismFilter))) && (!antibioticFilter || item.empiricRegimens.some((regimen) => regimen.components.some((component) => component.antibioticIds.includes(antibioticFilter))) || item.targetedTherapies.some((therapy) => therapy.antibioticIds.includes(antibioticFilter)));
  });
  const selected = filtered.find((item) => item.id === selectedId) ?? filtered[0];
  const selectPathway = (id: string) => { setSelectedId(id); const url = new URL(window.location.href); url.searchParams.set("pathway", id); window.history.replaceState(null, "", url); };
  const reset = () => { setQuery(""); setSite(""); setSetting(""); setPopulation(""); };

  return <div className="space-y-5">
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="grid gap-3 lg:grid-cols-[minmax(240px,1.5fr)_repeat(3,minmax(140px,1fr))_auto]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><span className="sr-only">질환 검색</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="질환명·영문명·alias 검색" className="w-full rounded-xl border border-slate-200 bg-slate-50 py-2.5 pl-10 pr-3 text-sm focus:border-teal-500 focus:outline-none" /></label><select value={site} onChange={(event) => setSite(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">모든 감염 부위</option>{sites.map((item) => <option key={item} value={item}>{SITE_LABELS[item] ?? item}</option>)}</select><select value={setting} onChange={(event) => setSetting(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">모든 감염 환경</option>{Object.entries(SETTING_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={population} onChange={(event) => setPopulation(event.target.value)} className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm"><option value="">모든 대상군</option>{Object.entries(POPULATION_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button type="button" onClick={reset} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm text-slate-600"><Filter className="h-4 w-4" />초기화</button></div><div className="mt-3 text-right text-xs text-slate-500">임상 경로 {filtered.length}/{clinicalPathways.length}개</div><label className="mt-4 block"><span className="text-xs font-semibold uppercase tracking-wide text-slate-500">질환별 항균치료 선택</span><select value={selected?.id ?? ""} onChange={(event) => selectPathway(event.target.value)} disabled={filtered.length === 0} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-semibold text-slate-900 disabled:opacity-50">{filtered.map((item) => <option key={item.id} value={item.id}>{item.displayName} · {SITE_LABELS[item.infectionSite] ?? item.infectionSite}</option>)}</select></label></section>
      <div className="space-y-5"><aside className="hidden">{filtered.map((item) => <button key={item.id} type="button" onClick={() => selectPathway(item.id)} className={`w-full rounded-xl border p-4 text-left transition ${selected?.id === item.id ? "border-teal-600 bg-teal-50 shadow-sm" : "border-slate-200 bg-white hover:border-teal-300"}`}><strong className="block text-sm text-slate-950">{item.displayName}</strong><span className="mt-2 block text-xs text-slate-500">{SITE_LABELS[item.infectionSite] ?? item.infectionSite} · {SETTING_LABELS[item.setting]}</span></button>)}{filtered.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 p-5 text-center text-sm text-slate-500">조건에 맞는 검증 경로가 없습니다.</div> : null}</aside>
      {selected ? <main className="space-y-4"><header className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex flex-wrap items-center gap-2 text-xs text-slate-500"><BookOpenCheck className="h-4 w-4 text-teal-700" />{selected.reviewStatus === "verified" ? "Verified" : "Reviewed"} · {selected.reviewedAt}</div><h1 className="mt-2 text-xl font-semibold text-slate-950 sm:text-2xl">{selected.displayName}</h1><div className="mt-3 flex flex-wrap gap-2">{selected.population.map((item) => <span key={item} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-700">{POPULATION_LABELS[item]}</span>)}{selected.severity.map((item) => <span key={item} className="rounded-full bg-slate-100 px-2.5 py-1 text-xs text-slate-700">{item}</span>)}</div><Link href={`/disease/${selected.diseaseSlug}`} className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-teal-700 hover:text-teal-900 hover:underline">기존 질환 노트 <ArrowUpRight className="h-4 w-4" /></Link></header>
      <section className="grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-sm font-bold"><FlaskConical className="h-4 w-4 text-teal-700" />진단·배양</div><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{selected.diagnosticNotes.map((item) => <li key={item}>• {item}</li>)}</ul></div><div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-sm font-bold"><Stethoscope className="h-4 w-4 text-teal-700" />Source control·stewardship</div><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-700">{[...selected.sourceControlNotes, ...selected.stewardshipNotes].map((item) => <li key={item}>• {item}</li>)}</ul></div></section>
      <section className="rounded-xl border border-slate-200 bg-white p-4 sm:p-5"><div className="flex items-center gap-2 text-sm font-bold"><Bug className="h-4 w-4 text-teal-700" />예상 원인균</div><div className="mt-4 space-y-4">{selected.pathogenGroups.map((group) => <div key={group.context}><h3 className="text-xs font-bold uppercase tracking-wide text-slate-500">{group.context}</h3><div className="mt-2 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{group.organisms.map((item) => { const organism = spectrum.organisms.find((entry) => entry.id === item.organismId); return organism ? <article key={item.organismId} className="rounded-lg border border-slate-200 p-3"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{organism.label}</strong><span className="text-[11px] text-teal-700">{LIKELIHOOD_LABELS[item.likelihood]}</span></div>{item.notes[0] ? <p className="mt-2 text-xs leading-5 text-slate-600">{item.notes[0]}</p> : null}<div className="mt-3 flex flex-wrap gap-2">{organism.microbiologySlug ? <Link href={`/microbiology/${organism.microbiologySlug}`} className="text-xs font-semibold text-teal-800 hover:underline">병원체 노트</Link> : null}<Link href={`?view=antibiotics&mode=organism&organism=${item.organismId}`} className="text-xs font-semibold text-slate-600 hover:text-teal-800">spectrum 보기</Link></div></article> : null; })}</div></div>)}</div></section>
      <section><div className="mb-3 flex items-center gap-2 text-sm font-bold"><Pill className="h-4 w-4 text-teal-700" />경험적 항균요법</div>{selected.empiricRegimens.length ? <div className="grid gap-3 lg:grid-cols-2">{selected.empiricRegimens.map((item) => <RegimenCard key={item.id} regimen={item} spectrum={spectrum} />)}</div> : <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><ShieldAlert className="mr-2 inline h-4 w-4" />이 질환은 고정된 단일 경험요법으로 제시하지 않습니다. 배양, 감염 환경과 전문팀 판단을 우선합니다.</div>}</section>
      {selected.targetedTherapies.length ? <section><div className="mb-3 text-sm font-bold">배양 후 표적치료 예시</div><div className="grid gap-3 md:grid-cols-2">{selected.targetedTherapies.map((therapy, index) => { const organism = spectrum.organisms.find((item) => item.id === therapy.organismId); return <article key={`${therapy.organismId}-${index}`} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-sm">{organism?.label ?? therapy.organismId}</strong><p className="mt-1 text-xs text-slate-500">{therapy.susceptibilityCondition}</p><div className="mt-3 flex flex-wrap gap-2">{therapy.antibioticIds.map((id) => { const drug = spectrum.antibiotics.find((item) => item.id === id); return drug ? <Link key={id} href={`/drugs/antibiotics?mode=antibiotic&antibiotic=${id}`} className="rounded-full bg-teal-50 px-3 py-1 text-xs font-semibold text-teal-900">{drug.inn}</Link> : null; })}</div>{therapy.notes.map((item) => <p key={item} className="mt-2 text-xs leading-5 text-slate-600">{item}</p>)}</article>; })}</div></section> : null}
      <section className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="text-xs font-bold uppercase tracking-wide text-slate-500">근거</div><div className="mt-3 flex flex-wrap gap-2">{selected.sourceIds.map((id) => { const source = dataset.sources.find((item) => item.id === id); return source ? <a key={id} href={source.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs text-teal-800 hover:border-teal-400">{source.label} ({source.year})<ArrowUpRight className="h-3 w-3" /></a> : null; })}</div></section>
      </main> : null}</div>
    <footer className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-600"><strong className="text-slate-800">해석 주의:</strong> {dataset.disclaimer} · 전체 검토일 {dataset.reviewedAt}</footer>
  </div>;
}
